// /virtio-blk-rw — multi-sector read/write driver (P4-Ic7).
//
// Closes ROADMAP §6.2's exit criterion:
//   "Userspace virtio-blk: read 1 GiB from VirtIO block device
//    successfully; write 1 GiB and read it back, verify bit-exact."
//
// Builds on virtio-blk-probe (P4-Ic5b2) by:
//   - using TWO kobj_dma allocations: a 4 KiB "ring" buffer for the
//     virtqueue rings + per-request header + status byte; a 1 MiB
//     "data" buffer that holds the per-request sector data
//     (= SECTORS_PER_REQUEST = 2048 sectors per descriptor chain).
//   - reading the VirtIO blk Capacity field (config-space offset 0)
//     and scaling the test bytes per pass to min(capacity - 1 sector,
//     MAX_PASS_BYTES). MAX_PASS_BYTES = 1 GiB so a 1 GiB disk image
//     produces a 1 GiB read pass + 1 GiB write pass + 1 GiB readback,
//     satisfying the exit criterion. Smaller disks scale down
//     proportionally.
//   - reusing the same 3-descriptor head every request (req / data /
//     status). desc[0] and desc[2] are written once; desc[1]'s
//     `flags` field flips between NEXT (for VIRTIO_BLK_T_OUT — device
//     reads data) and NEXT|WRITE (for VIRTIO_BLK_T_IN — device writes
//     data). avail.idx + used.idx track per-iteration progress.
//
// Three passes per invocation, on TWO non-overlapping regions:
//
//   READ region : sectors [1..pass_sectors+1). Holds pattern A baked
//                 in by tools/mkdisk.py. NEVER modified by this binary,
//                 so the test is idempotent (a re-run sees the same
//                 ground-truth bytes regardless of prior runs).
//
//   WRITE region: sectors [pass_sectors+1..2*pass_sectors+1). Pre-state
//                 is irrelevant (mkdisk.py also wrote pattern A there
//                 initially; a prior run may have left pattern B from
//                 its own pass B). Pass B overwrites the whole region
//                 with pattern B before pass C reads.
//
//   Pass A: READ + VERIFY pattern A over READ region. Mismatch → fail.
//   Pass B: WRITE pattern B over WRITE region. No per-sector verify.
//   Pass C: READ + VERIFY pattern B over WRITE region (write→readback).
//
// The two regions are non-overlapping (write starts at pass_sectors+1,
// one sector past the read region). The READ region is never touched
// by this binary, so re-runs are deterministic.
//
// Required disk size to meet the strict 1 GiB exit criterion: 2 GiB+.
// The binary auto-scales pass_bytes = min(half_usable_disk, 1 GiB).
// THYLACINE_DISK_SIZE=2G gives 1 GiB per pass = 1 GiB read + 1 GiB
// write + 1 GiB readback. Smaller disks scale down proportionally;
// the test still exercises the multi-sector r/w path but covers less
// territory per invocation.
//
// Pattern A is generated by tools/mkdisk.py at disk build time; the
// LCG constants are mirrored verbatim. Pattern B uses a distinct LCG
// keyed off (sector ^ PATTERN_B_SEED_XOR).
//
// IRQ wait policy: same as virtio-blk-probe. Each iteration kicks the
// device via REG_QUEUE_NOTIFY, sleeps on t_irq_wait, ACKs
// REG_INTERRUPT_STATUS, then validates used.idx + status byte (+
// data for read passes).
//
// Cap: per-pass max = 1 GiB even on larger disks. The exit criterion
// is exactly 1 GiB; arbitrary larger reads add boot-test time without
// proving anything new.

#![no_std]
#![no_main]

use core::arch::asm;
use libthyla_rs::{
    T_PROT_READ, T_PROT_WRITE, T_RIGHT_MAP, T_RIGHT_READ, T_RIGHT_SIGNAL,
    T_RIGHT_WRITE, t_dma_create, t_dma_map, t_exits, t_irq_create, t_irq_wait,
    t_mmio_create, t_mmio_map, t_puts, t_putstr,
};

// =============================================================================
// virtio-mmio bank constants — mirror of virtio-blk-probe.
// =============================================================================

const VIRTIO_MMIO_BASE_PA: u64 = 0x0a00_0000;
const VIRTIO_MMIO_SLOT_STRIDE: u64 = 0x200;
const VIRTIO_MMIO_NUM_SLOTS: u64 = 32;
const PAGE_SIZE: u64 = 0x1000;
const VIRTIO_MMIO_NUM_PAGES: u64 =
    (VIRTIO_MMIO_NUM_SLOTS * VIRTIO_MMIO_SLOT_STRIDE) / PAGE_SIZE;
const VIRTIO_MMIO_GIC_SPI_BASE: u32 = 16;
const VIRTIO_MMIO_GIC_INTID_BASE: u32 = 32 + VIRTIO_MMIO_GIC_SPI_BASE;

// User-VA layout.
const MMIO_USER_VA: u64 = 0x0050_0000;   // 4 pages → 0x500000..0x504000
const RING_USER_VA: u64 = 0x0060_0000;   // 1 page  → 0x600000..0x601000
const DATA_USER_VA: u64 = 0x0070_0000;   // 256 pages → 0x700000..0x800000

// =============================================================================
// VirtIO MMIO register offsets.
// =============================================================================

const REG_MAGIC_VALUE: u64       = 0x000;
const REG_VERSION: u64           = 0x004;
const REG_DEVICE_ID: u64         = 0x008;
const REG_DEVICE_FEATURES: u64   = 0x010;
const REG_DEVICE_FEATURES_SEL: u64 = 0x014;
const REG_DRIVER_FEATURES: u64   = 0x020;
const REG_DRIVER_FEATURES_SEL: u64 = 0x024;
const REG_QUEUE_SEL: u64         = 0x030;
const REG_QUEUE_NUM_MAX: u64     = 0x034;
const REG_QUEUE_NUM: u64         = 0x038;
const REG_QUEUE_READY: u64       = 0x044;
const REG_QUEUE_NOTIFY: u64      = 0x050;
const REG_INTERRUPT_STATUS: u64  = 0x060;
const REG_INTERRUPT_ACK: u64     = 0x064;
const REG_STATUS: u64            = 0x070;
const REG_QUEUE_DESC_LOW: u64    = 0x080;
const REG_QUEUE_DESC_HIGH: u64   = 0x084;
const REG_QUEUE_DRIVER_LOW: u64  = 0x090;
const REG_QUEUE_DRIVER_HIGH: u64 = 0x094;
const REG_QUEUE_DEVICE_LOW: u64  = 0x0a0;
const REG_QUEUE_DEVICE_HIGH: u64 = 0x0a4;
const REG_CONFIG: u64            = 0x100;     // device-specific config

const VIRTIO_MMIO_MAGIC: u32          = 0x7472_6976;
const VIRTIO_MMIO_VERSION_MODERN: u32 = 2;
const VIRTIO_DEVICE_ID_BLK: u32       = 2;

const STATUS_ACKNOWLEDGE: u32 = 1;
const STATUS_DRIVER: u32      = 2;
const STATUS_DRIVER_OK: u32   = 4;
const STATUS_FEATURES_OK: u32 = 8;
const STATUS_FAILED: u32      = 128;

const VIRTIO_F_VERSION_1_BIT_BANK1: u32 = 1 << 0;

const VIRTQ_DESC_F_NEXT: u16  = 1;
const VIRTQ_DESC_F_WRITE: u16 = 2;

const VIRTIO_BLK_T_IN: u32  = 0;
const VIRTIO_BLK_T_OUT: u32 = 1;
const VIRTIO_BLK_S_OK: u8 = 0;

// =============================================================================
// Ring DMA layout (single 4 KiB page).
// =============================================================================
//
// Holds descriptor table, avail ring, used ring, request header, and
// status byte. The data buffer is in a SEPARATE 1 MiB DMA allocation
// (the data buffer is too large to share a single kobj_dma with the
// rings + headers).
//
// VIRTIO 1.2 alignment: desc table 16-byte; avail ring 2-byte; used
// ring 4-byte. All chosen offsets respect these.

const QUEUE_SIZE: u16 = 16;
const RING_DMA_SIZE: u64 = PAGE_SIZE;

const DESC_OFF: u64   = 0x000;   // 16 × 16 B = 256 B
const AVAIL_OFF: u64  = 0x100;   // 4 + 16*2 = 36 B
const USED_OFF: u64   = 0x200;   // 4 + 16*8 = 132 B
const REQ_OFF: u64    = 0x300;   // 16 B
const STATUS_OFF: u64 = 0x310;   // 1 B

// =============================================================================
// Data DMA layout (1 MiB).
// =============================================================================

const SECTOR_SIZE: u64 = 512;
const DATA_DMA_SIZE: u64 = 1 << 20;                            // 1 MiB
const SECTORS_PER_REQUEST: u64 = DATA_DMA_SIZE / SECTOR_SIZE;   // 2048

// Maximum bytes per pass (= ROADMAP §6.2 exit criterion).
const MAX_PASS_BYTES: u64 = 1 << 30;

// =============================================================================
// Deterministic test patterns.
// =============================================================================
//
// Pattern A: per-sector LCG. Mirrored verbatim in tools/mkdisk.py.
// Each sector's 512 bytes = 64 little-endian u64s, advancing the LCG
// from initial state = sector_index.
//
// Pattern B: distinct LCG, keyed off (sector ^ PATTERN_B_SEED_XOR).
// The XOR seed-shift guarantees pattern_b(k) ≠ pattern_a(k) for all k
// (LCG-A and LCG-B have different (mul,inc); even if they accidentally
// converged, the seed XOR would un-converge them).

const PATTERN_A_MUL: u64 = 0x9E37_79B9_7F4A_7C15;
const PATTERN_A_INC: u64 = 0x1234_5678_90AB_CDEF;
const PATTERN_B_MUL: u64 = 0xBF58_476D_1CE4_E5B9;
const PATTERN_B_INC: u64 = 0x82F6_3B78_1656_67B1;
const PATTERN_B_SEED_XOR: u64 = 0xDEAD_BEEF_CAFE_BABE;

#[inline(always)]
fn advance(state: u64, mul: u64, inc: u64) -> u64 {
    state.wrapping_mul(mul).wrapping_add(inc)
}

// =============================================================================
// MMIO + memory access helpers — same idiom as virtio-blk-probe.
// =============================================================================

#[inline(always)]
unsafe fn read32(addr: u64) -> u32 { core::ptr::read_volatile(addr as *const u32) }
#[inline(always)]
unsafe fn write32(addr: u64, val: u32) { core::ptr::write_volatile(addr as *mut u32, val) }
#[inline(always)]
unsafe fn write16(addr: u64, val: u16) { core::ptr::write_volatile(addr as *mut u16, val) }
#[inline(always)]
unsafe fn read16(addr: u64) -> u16 { core::ptr::read_volatile(addr as *const u16) }
#[inline(always)]
unsafe fn write64(addr: u64, val: u64) { core::ptr::write_volatile(addr as *mut u64, val) }
#[inline(always)]
unsafe fn read64(addr: u64) -> u64 { core::ptr::read_volatile(addr as *const u64) }
#[inline(always)]
unsafe fn read_u8(addr: u64) -> u8 { core::ptr::read_volatile(addr as *const u8) }
#[inline(always)]
fn dsb_sy() { unsafe { asm!("dsb sy", options(nostack, preserves_flags)) } }

// =============================================================================
// Diagnostic helpers.
// =============================================================================

fn write_hex_u32(buf: &mut [u8; 10], val: u32) {
    buf[0] = b'0'; buf[1] = b'x';
    for i in 0..8 {
        let nibble = (val >> ((7 - i) * 4)) & 0xf;
        buf[2 + i] = if nibble < 10 { b'0' + nibble as u8 } else { b'a' + (nibble - 10) as u8 };
    }
}

fn write_dec_u64(buf: &mut [u8; 21], val: u64) -> usize {
    let mut n = val;
    let mut i = 21;
    if n == 0 { i -= 1; buf[i] = b'0'; return i; }
    while n > 0 { i -= 1; buf[i] = b'0' + (n % 10) as u8; n /= 10; }
    i
}

fn log(s: &str) { t_putstr(s); }
fn log_dec(val: u64) {
    let mut buf = [0u8; 21];
    let start = write_dec_u64(&mut buf, val);
    unsafe { t_puts(buf.as_ptr().add(start), 21 - start) };
}
fn log_hex32(val: u32) {
    let mut buf = [0u8; 10];
    write_hex_u32(&mut buf, val);
    unsafe { t_puts(buf.as_ptr(), 10) };
}

// =============================================================================
// MMIO bank setup.
// =============================================================================

fn claim_virtio_mmio_bank() -> Option<u64> {
    for i in 0..VIRTIO_MMIO_NUM_PAGES {
        let pa = VIRTIO_MMIO_BASE_PA + i * PAGE_SIZE;
        let va = MMIO_USER_VA + i * PAGE_SIZE;
        let rights = T_RIGHT_READ | T_RIGHT_WRITE | T_RIGHT_MAP;
        let prot = T_PROT_READ | T_PROT_WRITE;

        let h = unsafe { t_mmio_create(pa, PAGE_SIZE, rights) };
        if h < 0 {
            log("virtio-blk-rw: SYS_MMIO_CREATE failed for page ");
            log_dec(i); log("\n");
            return None;
        }
        let rc = unsafe { t_mmio_map(h, va, prot) };
        if rc < 0 {
            log("virtio-blk-rw: SYS_MMIO_MAP failed for page ");
            log_dec(i); log("\n");
            return None;
        }
    }
    Some(MMIO_USER_VA)
}

fn find_blk_slot(mmio_base_va: u64) -> Option<(u32, u64)> {
    for slot in 0..VIRTIO_MMIO_NUM_SLOTS {
        let slot_va = mmio_base_va + slot * VIRTIO_MMIO_SLOT_STRIDE;
        if unsafe { read32(slot_va + REG_MAGIC_VALUE) } != VIRTIO_MMIO_MAGIC { continue; }
        if unsafe { read32(slot_va + REG_DEVICE_ID) } == VIRTIO_DEVICE_ID_BLK {
            return Some((slot as u32, slot_va));
        }
    }
    None
}

// =============================================================================
// VirtIO 1.2 init (per §3.1.1) — same recipe as virtio-blk-probe.
// =============================================================================

fn init_device(slot_va: u64, ring_pa: u64) -> bool {
    unsafe { write32(slot_va + REG_STATUS, 0) };
    unsafe { write32(slot_va + REG_STATUS, STATUS_ACKNOWLEDGE) };
    unsafe { write32(slot_va + REG_STATUS, STATUS_ACKNOWLEDGE | STATUS_DRIVER) };

    unsafe { write32(slot_va + REG_DEVICE_FEATURES_SEL, 0) };
    let _dev_feat_lo = unsafe { read32(slot_va + REG_DEVICE_FEATURES) };
    unsafe { write32(slot_va + REG_DEVICE_FEATURES_SEL, 1) };
    let dev_feat_hi = unsafe { read32(slot_va + REG_DEVICE_FEATURES) };
    if dev_feat_hi & VIRTIO_F_VERSION_1_BIT_BANK1 == 0 {
        log("virtio-blk-rw: device lacks VIRTIO_F_VERSION_1\n");
        unsafe { write32(slot_va + REG_STATUS, STATUS_FAILED) };
        return false;
    }

    unsafe { write32(slot_va + REG_DRIVER_FEATURES_SEL, 0) };
    unsafe { write32(slot_va + REG_DRIVER_FEATURES, 0) };
    unsafe { write32(slot_va + REG_DRIVER_FEATURES_SEL, 1) };
    unsafe { write32(slot_va + REG_DRIVER_FEATURES, VIRTIO_F_VERSION_1_BIT_BANK1) };

    unsafe {
        write32(slot_va + REG_STATUS,
                STATUS_ACKNOWLEDGE | STATUS_DRIVER | STATUS_FEATURES_OK);
    };
    let status = unsafe { read32(slot_va + REG_STATUS) };
    if status & STATUS_FEATURES_OK == 0 {
        log("virtio-blk-rw: FEATURES_OK rejected; status=");
        log_hex32(status); log("\n");
        return false;
    }

    unsafe { write32(slot_va + REG_QUEUE_SEL, 0) };
    let num_max = unsafe { read32(slot_va + REG_QUEUE_NUM_MAX) };
    if num_max < QUEUE_SIZE as u32 {
        log("virtio-blk-rw: QueueNumMax ("); log_dec(num_max as u64);
        log(") below QUEUE_SIZE\n");
        unsafe { write32(slot_va + REG_STATUS, STATUS_FAILED) };
        return false;
    }
    unsafe { write32(slot_va + REG_QUEUE_NUM, QUEUE_SIZE as u32) };

    let desc_pa = ring_pa + DESC_OFF;
    let avail_pa = ring_pa + AVAIL_OFF;
    let used_pa = ring_pa + USED_OFF;
    unsafe {
        write32(slot_va + REG_QUEUE_DESC_LOW,    (desc_pa  & 0xFFFF_FFFF) as u32);
        write32(slot_va + REG_QUEUE_DESC_HIGH,   (desc_pa  >> 32)         as u32);
        write32(slot_va + REG_QUEUE_DRIVER_LOW,  (avail_pa & 0xFFFF_FFFF) as u32);
        write32(slot_va + REG_QUEUE_DRIVER_HIGH, (avail_pa >> 32)         as u32);
        write32(slot_va + REG_QUEUE_DEVICE_LOW,  (used_pa  & 0xFFFF_FFFF) as u32);
        write32(slot_va + REG_QUEUE_DEVICE_HIGH, (used_pa  >> 32)         as u32);
    };

    unsafe { write32(slot_va + REG_QUEUE_READY, 1) };
    unsafe {
        write32(slot_va + REG_STATUS,
                STATUS_ACKNOWLEDGE | STATUS_DRIVER | STATUS_FEATURES_OK | STATUS_DRIVER_OK);
    };
    true
}

// =============================================================================
// Descriptor chain setup.
// =============================================================================
//
// Per request: desc[0..3) form the chain (req header → data → status).
// desc[0] (req header) is OUT (device-readable) and never changes.
// desc[2] (status byte) is IN/WRITE (device-writable) and never changes.
// desc[1] (data) flips between IN and OUT depending on the request
// direction; .addr / .len stay constant.
//
// We initialize desc[0] + desc[2] once before the loop; desc[1].flags
// is mutated per request.

fn init_descriptors(ring_va: u64, ring_pa: u64, data_pa: u64, data_len: u32) {
    let desc_va = ring_va + DESC_OFF;

    // desc[0]: req header (OUT to device).
    unsafe {
        write64(desc_va +  0, ring_pa + REQ_OFF);
        write32(desc_va +  8, 16);
        write16(desc_va + 12, VIRTQ_DESC_F_NEXT);
        write16(desc_va + 14, 1);
    };

    // desc[1]: data — .flags filled per request, but addr/len/next stable.
    unsafe {
        write64(desc_va + 16, data_pa);
        write32(desc_va + 24, data_len);
        // flags written in submit_request().
        write16(desc_va + 30, 2);
    };

    // desc[2]: status (IN; device writes 1 byte).
    unsafe {
        write64(desc_va + 32, ring_pa + STATUS_OFF);
        write32(desc_va + 40, 1);
        write16(desc_va + 44, VIRTQ_DESC_F_WRITE);
        write16(desc_va + 46, 0);
    };
}

// =============================================================================
// Submit + complete one request.
// =============================================================================

#[derive(Copy, Clone, PartialEq, Eq)]
enum Direction { Read, Write }

fn submit_request(
    slot_va: u64,
    ring_va: u64,
    sector: u64,
    sectors: u32,
    direction: Direction,
    avail_idx_local: u16,
) {
    // Pre-poison the status byte so a missing device write surfaces.
    unsafe { core::ptr::write_volatile((ring_va + STATUS_OFF) as *mut u8, 0xff) };

    // Update the request header (type + sector).
    let req_type = match direction {
        Direction::Read  => VIRTIO_BLK_T_IN,
        Direction::Write => VIRTIO_BLK_T_OUT,
    };
    let req_va = ring_va + REQ_OFF;
    unsafe {
        write32(req_va + 0, req_type);
        write32(req_va + 4, 0);
        write64(req_va + 8, sector);
    };

    // Update desc[1] length + flags. addr/next are stable. data_len varies
    // only if the LAST request is partial, but we round test_bytes down
    // to SECTORS_PER_REQUEST-multiples, so it's always SECTORS_PER_REQUEST.
    let _ = sectors;  // assertable: sectors == SECTORS_PER_REQUEST today
    let desc_va = ring_va + DESC_OFF;
    let data_flags = match direction {
        Direction::Read  => VIRTQ_DESC_F_NEXT | VIRTQ_DESC_F_WRITE,
        Direction::Write => VIRTQ_DESC_F_NEXT,
    };
    unsafe { write16(desc_va + 16 + 12, data_flags) };

    // Avail ring: ring[idx % QUEUE_SIZE] = head id (= 0, fixed).
    let avail_va = ring_va + AVAIL_OFF;
    let slot = (avail_idx_local as u64) % (QUEUE_SIZE as u64);
    unsafe { write16(avail_va + 4 + slot * 2, 0) };

    // Memory barrier: descriptor + ring writes visible before idx bump.
    dsb_sy();

    // Bump avail.idx.
    let new_idx = avail_idx_local.wrapping_add(1);
    unsafe { write16(avail_va + 2, new_idx) };

    dsb_sy();
    // Kick the device.
    unsafe { write32(slot_va + REG_QUEUE_NOTIFY, 0) };
}

#[derive(Copy, Clone, PartialEq, Eq)]
enum CompletionError {
    IrqError,
    UsedIdxMismatch,
    UsedIdMismatch,
    StatusByte,
}

fn wait_completion(
    irq_handle: i64,
    slot_va: u64,
    ring_va: u64,
    expected_used_idx: u16,
) -> Result<(), CompletionError> {
    let count = unsafe { t_irq_wait(irq_handle) };
    if count < 0 { return Err(CompletionError::IrqError); }

    let int_status = unsafe { read32(slot_va + REG_INTERRUPT_STATUS) };
    unsafe { write32(slot_va + REG_INTERRUPT_ACK, int_status) };

    let used_va = ring_va + USED_OFF;
    let used_idx = unsafe { read16(used_va + 2) };
    if used_idx != expected_used_idx { return Err(CompletionError::UsedIdxMismatch); }

    let slot = ((expected_used_idx as u64).wrapping_sub(1)) % (QUEUE_SIZE as u64);
    let used_id = unsafe { read32(used_va + 4 + slot * 8) };
    if used_id != 0 { return Err(CompletionError::UsedIdMismatch); }

    let status = unsafe { read_u8(ring_va + STATUS_OFF) };
    if status != VIRTIO_BLK_S_OK { return Err(CompletionError::StatusByte); }
    Ok(())
}

// =============================================================================
// Pattern generation + verification.
// =============================================================================
//
// Per sector: 64 LCG iterations × 8 bytes each = 512 bytes.
// Verification reads u64s from the data buffer and compares to the
// freshly-generated LCG value — no allocation, no extra buffers.
// (On AArch64 little-endian, host u64 == on-disk little-endian u64.)

fn fill_data_buffer(direction_pattern: Pattern, data_va: u64, start_sector: u64, count: u64) {
    let (mul, inc, xor) = direction_pattern.constants();
    for s in 0..count {
        let sec_va = data_va + s * SECTOR_SIZE;
        let mut state = (start_sector + s) ^ xor;
        for i in 0..64u64 {
            state = advance(state, mul, inc);
            unsafe { write64(sec_va + i * 8, state) };
        }
    }
}

// Returns Ok(()) on success, Err(sector_index_of_first_mismatch).
fn verify_data_buffer(
    direction_pattern: Pattern,
    data_va: u64,
    start_sector: u64,
    count: u64,
) -> Result<(), u64> {
    let (mul, inc, xor) = direction_pattern.constants();
    for s in 0..count {
        let sec_va = data_va + s * SECTOR_SIZE;
        let sector = start_sector + s;
        let mut state = sector ^ xor;
        for i in 0..64u64 {
            state = advance(state, mul, inc);
            let got = unsafe { read64(sec_va + i * 8) };
            if got != state { return Err(sector); }
        }
    }
    Ok(())
}

#[derive(Copy, Clone)]
enum Pattern { A, B }

impl Pattern {
    fn constants(self) -> (u64, u64, u64) {
        match self {
            Pattern::A => (PATTERN_A_MUL, PATTERN_A_INC, 0),
            Pattern::B => (PATTERN_B_MUL, PATTERN_B_INC, PATTERN_B_SEED_XOR),
        }
    }
}

// =============================================================================
// Single multi-sector pass (read OR write, fixed pattern).
// =============================================================================

fn run_pass(
    label: &str,
    direction: Direction,
    pattern: Pattern,
    slot_va: u64,
    ring_va: u64,
    data_va: u64,
    irq_handle: i64,
    start_sector: u64,
    total_sectors: u64,
    avail_idx_in: u16,
) -> Result<u16, u64> {
    log("virtio-blk-rw: pass "); log(label);
    log(" — sectors=["); log_dec(start_sector);
    log(".."); log_dec(start_sector + total_sectors);
    log(") = "); log_dec(total_sectors * SECTOR_SIZE);
    log(" bytes\n");

    let mut avail_idx_local = avail_idx_in;
    let mut remaining = total_sectors;
    let mut cursor = start_sector;

    while remaining > 0 {
        // Pre-fill data for write requests so the page mappings exist
        // AND the bytes the device will read are the expected pattern.
        if direction == Direction::Write {
            fill_data_buffer(pattern, data_va, cursor, SECTORS_PER_REQUEST);
            // For writes, ensure the CPU's stores are visible to the
            // device before kicking (the descriptor-bump dsb_sy in
            // submit_request also covers this, but an extra dsb_sy
            // here is cheap and documents the intent).
            dsb_sy();
        }

        submit_request(slot_va, ring_va, cursor, SECTORS_PER_REQUEST as u32, direction, avail_idx_local);
        let expected = avail_idx_local.wrapping_add(1);
        match wait_completion(irq_handle, slot_va, ring_va, expected) {
            Ok(()) => {}
            Err(_e) => {
                log("virtio-blk-rw: FAIL — completion error at sector ");
                log_dec(cursor); log("\n");
                return Err(cursor);
            }
        }

        // For read requests, verify the bytes we just received.
        if direction == Direction::Read {
            // dsb_sy here would be redundant: the device's writes
            // landed before kobj_irq_dispatch incremented pending,
            // and t_irq_wait synchronizes through the kernel scheduler
            // path which is itself a full barrier.
            if let Err(bad) = verify_data_buffer(pattern, data_va, cursor, SECTORS_PER_REQUEST) {
                log("virtio-blk-rw: FAIL — pattern mismatch at sector ");
                log_dec(bad); log(" (pass "); log(label); log(")\n");
                return Err(bad);
            }
        }

        avail_idx_local = expected;
        cursor += SECTORS_PER_REQUEST;
        remaining -= SECTORS_PER_REQUEST;
    }

    log("virtio-blk-rw: pass "); log(label); log(" OK\n");
    Ok(avail_idx_local)
}

// =============================================================================
// Entry point.
// =============================================================================

// Pre-touch the second page of our LOAD segment.
//
// The v1.0 kernel does not yet implement uaccess-fault recovery:
// SYS_PUTS dereferences the user-VA pointer directly in kernel mode
// (kernel/syscall.c::sys_puts_handler). If a .rodata string lives at
// user-VA 0x401XXX and that page hasn't been demand-paged yet, the
// kernel dereference takes an UNHANDLED translation fault.
//
// Forcing the page to fault from user mode (where userland_demand_page
// maps it) before any SYS_PUTS makes the kernel-side dereferences hit
// already-mapped PTEs.
//
// We touch ONLY 0x401000 (page 1 of the LOAD segment) because the
// current binary's memsz rounds to 0x2000 (2 pages). Touching 0x402000
// would land past the BURROW and SIGSEGV. If the binary later grows
// past 0x402000 (memsz > 0x2000), extend this loop.
//
// Underlying fix lives in Phase 5 (uaccess-emulation in kernel syscall
// handlers); until then, this is the per-binary discipline.
#[inline(never)]
fn pretouch_rodata_pages() {
    const ROD_PAGE_1: u64 = 0x401000;
    unsafe { let _ = core::ptr::read_volatile(ROD_PAGE_1 as *const u8); }
}

#[no_mangle]
pub extern "C" fn rs_main() -> i64 {
    // Pre-touch our LOAD segment's pages so SYS_PUTS doesn't kernel-
    // fault on .rodata strings beyond page 0. (See pretouch_rodata_pages
    // comment.)
    pretouch_rodata_pages();

    // Phase 1: claim + map virtio-mmio bank.
    let mmio_base = match claim_virtio_mmio_bank() {
        Some(va) => va,
        None => {
            log("virtio-blk-rw: FAIL — virtio-mmio bank claim failed\n");
            unsafe { t_exits(1) };
        }
    };

    // Phase 2: locate the block device.
    let (slot, slot_va) = match find_blk_slot(mmio_base) {
        Some(f) => f,
        None => {
            log("virtio-blk-rw: SKIP — no virtio-blk-device\n");
            return 0;
        }
    };
    let intid = VIRTIO_MMIO_GIC_INTID_BASE + slot;

    let version = unsafe { read32(slot_va + REG_VERSION) };
    if version != VIRTIO_MMIO_VERSION_MODERN {
        log("virtio-blk-rw: FAIL — slot reports legacy version (");
        log_dec(version as u64); log(")\n");
        unsafe { t_exits(1) };
    }

    // Phase 3: IRQ.
    let irq_handle = unsafe { t_irq_create(intid, T_RIGHT_SIGNAL) };
    if irq_handle < 0 {
        log("virtio-blk-rw: FAIL — SYS_IRQ_CREATE\n");
        unsafe { t_exits(1) };
    }

    // Phase 4: ring DMA (4 KiB).
    let ring_handle = unsafe {
        t_dma_create(RING_DMA_SIZE, T_RIGHT_READ | T_RIGHT_WRITE | T_RIGHT_MAP)
    };
    if ring_handle < 0 {
        log("virtio-blk-rw: FAIL — ring SYS_DMA_CREATE\n");
        unsafe { t_exits(1) };
    }
    let ring_pa = unsafe { t_dma_map(ring_handle, RING_USER_VA, T_PROT_READ | T_PROT_WRITE) };
    if ring_pa < 0 {
        log("virtio-blk-rw: FAIL — ring SYS_DMA_MAP\n");
        unsafe { t_exits(1) };
    }

    // Phase 5: data DMA (1 MiB).
    let data_handle = unsafe {
        t_dma_create(DATA_DMA_SIZE, T_RIGHT_READ | T_RIGHT_WRITE | T_RIGHT_MAP)
    };
    if data_handle < 0 {
        log("virtio-blk-rw: FAIL — data SYS_DMA_CREATE\n");
        unsafe { t_exits(1) };
    }
    let data_pa = unsafe { t_dma_map(data_handle, DATA_USER_VA, T_PROT_READ | T_PROT_WRITE) };
    if data_pa < 0 {
        log("virtio-blk-rw: FAIL — data SYS_DMA_MAP\n");
        unsafe { t_exits(1) };
    }

    // Pre-touch DMA pages so userland_demand_page installs them.
    // Without this, the first write_volatile during pattern fill or
    // descriptor setup would page-fault; the BURROW_TYPE_DMA arm of
    // demand_page handles it via burrow_acquire_mapping but in a
    // no_std + no_unwind context the cleanest path is the touch loop.
    for off in (0..RING_DMA_SIZE).step_by(PAGE_SIZE as usize) {
        unsafe { core::ptr::write_volatile((RING_USER_VA + off) as *mut u8, 0) };
    }
    for off in (0..DATA_DMA_SIZE).step_by(PAGE_SIZE as usize) {
        unsafe { core::ptr::write_volatile((DATA_USER_VA + off) as *mut u8, 0) };
    }

    // Phase 6: VirtIO init.
    if !init_device(slot_va, ring_pa as u64) {
        unsafe { t_exits(1) };
    }

    // Phase 7: capacity → per-pass byte budget.
    // VirtIO blk config-space §5.2.4: u64 `capacity` at config offset 0,
    // in 512-byte sectors.
    let capacity_lo = unsafe { read32(slot_va + REG_CONFIG + 0) } as u64;
    let capacity_hi = unsafe { read32(slot_va + REG_CONFIG + 4) } as u64;
    let capacity_sectors = capacity_lo | (capacity_hi << 32);
    let capacity_bytes = capacity_sectors * SECTOR_SIZE;

    // Reserve sector 0 (signature owned by P4-Ic5b2's virtio-blk-probe).
    // Split the remaining sectors in HALF: lower half = READ region
    // (sectors [1..pass_sectors+1), pattern A, never modified); upper
    // half = WRITE region (sectors [pass_sectors+1..2*pass_sectors+1),
    // pass B overwrites with pattern B then pass C verifies).
    //
    // Non-overlapping layout → idempotent across re-runs (the READ
    // region stays at pattern A regardless of prior test invocations).
    let usable_bytes = capacity_bytes.saturating_sub(SECTOR_SIZE);
    let half_bytes = usable_bytes / 2;
    let granularity = SECTORS_PER_REQUEST * SECTOR_SIZE;
    let mut pass_bytes = (half_bytes / granularity) * granularity;
    if pass_bytes > MAX_PASS_BYTES { pass_bytes = MAX_PASS_BYTES; }

    log("virtio-blk-rw: slot=");      log_dec(slot as u64);
    log(" intid=");                    log_dec(intid as u64);
    log(" capacity_sectors=");         log_dec(capacity_sectors);
    log(" → per-pass=");               log_dec(pass_bytes);
    log(" bytes ("); log_dec(pass_bytes / granularity);
    log(" requests × 1 MiB)\n");

    if pass_bytes == 0 {
        log("virtio-blk-rw: FAIL — disk too small for any 1 MiB request in EACH of two non-overlapping regions (need >= 4 MiB disk)\n");
        unsafe { t_exits(1) };
    }
    let pass_sectors = pass_bytes / SECTOR_SIZE;
    let read_start  = 1u64;
    let write_start = read_start + pass_sectors;

    // Phase 8: descriptor table setup. The chain is reused every
    // request; we only need to set desc[0..3) once. desc[1].flags
    // gets rewritten per request inside submit_request().
    init_descriptors(RING_USER_VA, ring_pa as u64, data_pa as u64, DATA_DMA_SIZE as u32);

    // Phase 9: three passes.
    let mut avail_idx = 0u16;

    // Pass A: read-and-verify pattern A over the READ region.
    avail_idx = match run_pass(
        "A read+verify(A)",
        Direction::Read, Pattern::A,
        slot_va, RING_USER_VA, DATA_USER_VA, irq_handle,
        read_start, pass_sectors, avail_idx,
    ) { Ok(v) => v, Err(_) => unsafe { t_exits(1) } };

    // Pass B: write pattern B over the WRITE region (disjoint from READ).
    avail_idx = match run_pass(
        "B write(B)",
        Direction::Write, Pattern::B,
        slot_va, RING_USER_VA, DATA_USER_VA, irq_handle,
        write_start, pass_sectors, avail_idx,
    ) { Ok(v) => v, Err(_) => unsafe { t_exits(1) } };

    // Pass C: read-back, verify pattern B over the WRITE region.
    let _ = match run_pass(
        "C read+verify(B)",
        Direction::Read, Pattern::B,
        slot_va, RING_USER_VA, DATA_USER_VA, irq_handle,
        write_start, pass_sectors, avail_idx,
    ) { Ok(v) => v, Err(_) => unsafe { t_exits(1) } };

    log("virtio-blk-rw: PASS — read(A)+write(B)+readback(B) over ");
    log_dec(pass_bytes); log(" bytes per pass × 3 passes (READ region [");
    log_dec(read_start); log("..");   log_dec(read_start + pass_sectors);
    log("), WRITE region ["); log_dec(write_start); log("..");
    log_dec(write_start + pass_sectors); log("))\n");
    0
}
