// Generated by tools/bake-lictor.py; do not edit.
fn metrics(font: Font) -> (usize, usize, usize) { match font {
    Font::Label => (0, 16, 17),
    Font::Body => (26481, 17, 20),
    Font::Section => (59558, 19, 21),
    Font::Identity => (98358, 21, 26),
    Font::Title => (151417, 32, 41),
    Font::SmallMono => (278778, 9, 14),
    Font::Rail => (291097, 10, 16),
    Font::Mono => (306714, 11, 20),
} }
