// Generate cross-implementation known-answer vectors for the npxf secure
// channel, for Thylacine's guest-side client (usr/forage) to be pinned against.
//
// THE POINT OF THE #include: `derive`, `absorb`, `transcript_start`,
// `confirm_tag` and `expand_label` live in channel.cpp's ANONYMOUS namespace,
// so a generator that linked against channel.o could not reach them and would
// have to RE-DERIVE the key schedule from the public primitives. That is
// exactly the failure this file must not have: a re-derivation is my reading of
// channel.cpp, so if I misread it, the generator and the Rust it pins would
// agree with each other and not with npxf. Including the translation unit makes
// the vectors come from npxf's REAL code.
#include "../src/channel.cpp"

#include <cstdio>
#include <string>

using namespace npxf;

static void emit(const char *name, const uint8_t *p, size_t n) {
    std::printf("%-12s = %s\n", name, to_hex({p, n}).c_str());
}

int main() {
    // Fixed inputs. Nothing here is secret -- these are test vectors, and the
    // ephemerals are deliberately pinned so the whole schedule is deterministic.
    const std::string token = "thylacine-npxf-kat-token";

    uint8_t ce_sk[32], se_sk[32];
    for (int i = 0; i < 32; i++) ce_sk[i] = uint8_t(0x10 + i);
    for (int i = 0; i < 32; i++) se_sk[i] = uint8_t(0xA0 + i);

    std::printf("# npxf secure-channel known-answer vectors\n");
    std::printf("# Generated by scratchpad/npxf_kat.cpp against npxf's own\n");
    std::printf("# channel.cpp -- see that file's header for why it #includes it.\n");
    std::printf("# All values hex, lowercase, no separators.\n\n");

    std::printf("%-12s = %s\n", "token_ascii", token.c_str());
    emit("token", reinterpret_cast<const uint8_t *>(token.data()), token.size());

    crypto::Key psk = derive_psk(byte_span(std::string_view(token)));
    emit("psk", psk.data(), psk.size());

    uint8_t ce_pk[32], se_pk[32];
    crypto::x25519_base(ce_sk, ce_pk);
    crypto::x25519_base(se_sk, se_pk);
    emit("ce_sk", ce_sk, 32);
    emit("ce_pk", ce_pk, 32);
    emit("se_sk", se_sk, 32);
    emit("se_pk", se_pk, 32);

    // Flight 1, exactly as client_handshake builds it.
    uint8_t msg1[kHandshakeMsg1];
    std::memcpy(msg1, "NPXF", 4);
    msg1[4] = kProtocolVersion;
    msg1[5] = msg1[6] = msg1[7] = 0;
    std::memcpy(msg1 + 8, ce_pk, 32);
    emit("msg1", msg1, sizeof msg1);

    crypto::Hash h0 = transcript_start();
    crypto::Hash h1 = absorb(h0, msg1, sizeof msg1);
    crypto::Hash h2 = absorb(h1, se_pk, 32);
    emit("h0", h0.data(), h0.size());
    emit("h1", h1.data(), h1.size());
    emit("h2", h2.data(), h2.size());

    // The raw DH, and the proof both sides land on it.
    uint8_t dh_c[32], dh_s[32];
    if (!crypto::x25519(ce_sk, se_pk, dh_c)) { std::fprintf(stderr, "client dh failed\n"); return 1; }
    if (!crypto::x25519(se_sk, ce_pk, dh_s)) { std::fprintf(stderr, "server dh failed\n"); return 1; }
    if (std::memcmp(dh_c, dh_s, 32) != 0) { std::fprintf(stderr, "dh disagree\n"); return 1; }
    emit("dh", dh_c, 32);

    uint8_t prk[32];
    crypto::hkdf_extract(std::span<const uint8_t>(psk.data(), psk.size()),
                         std::span<const uint8_t>(dh_c, 32), prk);
    emit("prk", prk, 32);

    // npxf's OWN derive(), from the included translation unit.
    Derived d;
    derive(psk, ce_sk, se_pk, h2, d);
    emit("k_c2s", d.c2s.data(), d.c2s.size());
    emit("k_s2c", d.s2c.data(), d.s2c.size());
    emit("k_cfm", d.cfm.data(), d.cfm.size());

    uint8_t tag_server[32], tag_client[32];
    confirm_tag(d.cfm, "server", tag_server);
    confirm_tag(d.cfm, "client", tag_client);
    emit("tag_server", tag_server, 32);
    emit("tag_client", tag_client, 32);

    // Flights 2 and 3 as they appear on the wire.
    uint8_t msg2[kHandshakeMsg2];
    std::memcpy(msg2, se_pk, 32);
    std::memcpy(msg2 + 32, tag_server, 32);
    emit("msg2", msg2, sizeof msg2);
    emit("msg3", tag_client, 32);

    // Record layer. The plaintext is a real 9P Tversion so the fixture also
    // documents what actually rides this channel.
    const uint8_t tversion[] = {
        0x15, 0x00, 0x00, 0x00,                        // size[4] = 21, header included
        100,                                            // Tversion
        0xff, 0xff,                                     // tag = NOTAG
        0x00, 0x20, 0x00, 0x00,                         // msize = 8192
        0x08, 0x00,                                     // version[s]: 8 bytes follow
        '9', 'P', '2', '0', '0', '0', '.', 'L',
    };
    // Both halves of the frame must agree, or the fixture teaches the wrong
    // thing: the array is 21 bytes AND its own size[4] says so.
    static_assert(sizeof tversion == 21, "the fixture plaintext must be 21 bytes");
    if (ld32(tversion) != sizeof tversion) {
        std::fprintf(stderr, "fixture size[4] disagrees with its own length\n");
        return 1;
    }
    emit("record_pt", tversion, sizeof tversion);

    // Two records under the SAME key at counters 0 and 1. Emitting both is what
    // pins the per-direction counter: an implementation that reused nonce 0
    // would match record0 and fail record1.
    for (uint64_t ctr = 0; ctr < 2; ctr++) {
        Bytes rec(4 + sizeof tversion + crypto::kTagLen);
        st32(rec.data(), uint32_t(sizeof tversion + crypto::kTagLen));
        uint8_t nonce[crypto::kNonceLen];
        std::memset(nonce, 0, 4);
        st64(nonce + 4, ctr);
        crypto::aead_seal(d.c2s.data(), nonce, std::span<const uint8_t>(rec.data(), 4), tversion,
                          sizeof tversion, rec.data() + 4, rec.data() + 4 + sizeof tversion);
        char name[16];
        std::snprintf(name, sizeof name, "record_c2s%llu", (unsigned long long)ctr);
        emit(name, rec.data(), rec.size());
    }

    return 0;
}
