// haul -- mount a remote 9P2000.L tree served over TCP.
//
// A thylacine hauled a kill back to cover to eat it. This drags a tree from
// outside the machine into the local namespace, and the pages it yields are
// cached by the Larder (the guest-side FS cache, I-38).
//
// Named per CLAUDE.md "Thematic naming", operator-ratified 2026-09-09. It was
// `forage` for one day, which collided with `tools/forage.sh`, the build-input
// collector -- same metaphor, different layer, and the two are confusable in
// prose even though they never co-occur on a command line. `mount` and `srv`
// are the Plan 9 words; `quarry`, `prowl` and `larder` are taken.
//
//   haul [-a aname] host!port mountpoint
//   haul -t /cfg/npxf.token '10.0.2.2!5640' /n/host
//
// WHY A USERSPACE SHIM AT ALL. The kernel's 9P client speaks 9P2000.L over a
// BYTE PIPE, not over TCP: `9p_spoor_transport` moves messages across a pair of
// Spoors, and there is no in-kernel socket transport (there is deliberately no
// TCP in the kernel at all -- netd owns the stack). SYS_ATTACH_9P's own doc
// names the way across:
//
//     "For half-duplex (Plan 9 pipes from SYS_PIPE), userspace creates two
//      pipe pairs and passes the matching write-end and read-end."
//
// So haul holds the SERVER ends of two pipes, hands the CLIENT ends to
// SYS_ATTACH_9P, and shuttles bytes between those and the TCP connection. The
// kernel believes it is talking to a local 9P server; the server believes it is
// talking to a local 9P client. `usr/viv` already drives this exact attach for
// the container diorama -- the pattern is live, not new.
//
// THE ORDERING THAT MATTERS. SYS_ATTACH_9P performs Tversion + Tattach
// SYNCHRONOUSLY inside the syscall, so it blocks until replies arrive. Nothing
// can reply unless the pumps are already running. Hence: spawn both pump
// threads FIRST, then attach from the main thread. Reversing those two
// deadlocks -- the kernel waits for an Rversion that only a thread that has not
// been spawned could deliver.
//
// FRAMED, NOT BLIND. A plain byte splice would be correct for the plaintext
// case (9P over TCP is just the stream). The pump parses the 9P `size[4]`
// prefix anyway, for two reasons: the npxf secure channel seals ONE 9P MESSAGE
// PER AEAD RECORD and so needs message boundaries, and framing lets a hostile
// or confused peer's absurd length claim be refused HERE rather than handed
// inward. That is what made the npxf layer a swap of the pump's read/write pair
// rather than a rewrite of it.
//
// THE SECURE CHANNEL (`-t` / `--token-env`). With a token, haul runs npxf's
// three-flight handshake on the socket before anything else and then carries
// every 9P message as one AEAD record. The protocol lives in `npxf.rs` -- pure,
// syscall-free, and pinned byte for byte to vectors generated by npxf's own
// implementation. Only the I/O is here.
//
// THE EPHEMERAL COMES FROM THE KERNEL CSPRNG, OR THE MOUNT FAILS. Forward
// secrecy rests entirely on that scalar being unpredictable, so there is no
// fallback source and no "degraded" mode: SYS_GETRANDOM (CAP_CSPRNG_READ) works
// or haul refuses to connect.

#![no_std]
#![no_main]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use core::sync::atomic::{AtomicU32, Ordering};

use haul::npxf;
use libthyla_rs::env::{self, Args};
use zeroize::Zeroize;
use libthyla_rs::io::Read;
use libthyla_rs::net::{Ipv4Addr, SocketAddrV4, TcpStream};
use libthyla_rs::thread;
use libthyla_rs::{
    t_attach_9p, t_burrow_attach, t_close, t_mount, t_pipe, t_putstr, T_MREPL,
};

#[global_allocator]
static GLOBAL_ALLOCATOR: libthyla_rs::alloc::ThylaAlloc = libthyla_rs::alloc::ThylaAlloc;

macro_rules! say {
    ($($a:tt)*) => {{
        let mut s = alloc::format!($($a)*);
        s.push('\n');
        let _ = libthyla_rs::t_putstr(&s);
    }};
}

/// Progress, under `-v`.
///
/// Not debug scaffolding: every step below can BLOCK -- the dial, the
/// handshake's two reads, and the attach (which drives Tversion + Tattach
/// synchronously inside the syscall). A haul that is merely slow and a haul
/// that is wedged look identical without this, which is exactly the state the
/// first guest run left us in: ninety seconds of silence and no way to say
/// which syscall owned them.
static VERBOSE: AtomicU32 = AtomicU32::new(0);

macro_rules! step {
    ($($a:tt)*) => {{
        if VERBOSE.load(Ordering::Relaxed) != 0 {
            let mut s = alloc::string::String::from("haul: .. ");
            s.push_str(&alloc::format!($($a)*));
            s.push('\n');
            let _ = libthyla_rs::t_putstr(&s);
        }
    }};
}

/// The largest 9P message haul will relay in either direction.
///
/// A 9P message is `size[4]` INCLUDING those four bytes, so this bounds the
/// whole frame. It is a shim-side ceiling, not the negotiated msize: haul
/// does not parse Tversion (it is a transport, not a client), so it cannot know
/// what the two ends agreed on. 1 MiB is far above any msize the kernel
/// negotiates and far below a length a hostile peer could use to make us
/// allocate the heap -- which is the point of having it at all.
const MSG_MAX: u32 = 1024 * 1024;

/// A 9P message is at minimum `size[4] type[1] tag[2]`. npxf's server refuses
/// anything shorter as a runt; matching it here means a malformed frame dies at
/// the transport instead of being handed to a parser on either side.
const MSG_MIN: u32 = 7;

/// Per-pump stack. One page is ample -- a pump's frame is a buffer pointer and
/// a few counters; the message buffer itself is heap.
const PUMP_STACK: u64 = 64 * 1024;

/// Set by whichever pump stops first, so the survivor's diagnosis names the
/// side that actually ended rather than the side that noticed, and so the main
/// thread learns the transport is over.
static STOPPED: AtomicU32 = AtomicU32::new(0);

const STOP_NONE: u32 = 0;
const STOP_UP: u32 = 1; // kernel -> server direction ended
const STOP_DOWN: u32 = 2; // server -> kernel direction ended

/// Read exactly `buf.len()` bytes, or report short. A single `read` on either a
/// pipe or a TCP stream may return less than asked for, and a 9P frame that is
/// split across two reads is the ordinary case, not the exceptional one.
fn read_exact(fd: i64, buf: &mut [u8]) -> bool {
    let mut off = 0usize;
    while off < buf.len() {
        let n = unsafe { libthyla_rs::t_read(fd, buf[off..].as_mut_ptr(), buf.len() - off) };
        if n <= 0 {
            return false; // EOF or error: the caller treats both as "channel over"
        }
        off += n as usize;
    }
    true
}

fn write_exact(fd: i64, buf: &[u8]) -> bool {
    let mut off = 0usize;
    while off < buf.len() {
        let n = unsafe { libthyla_rs::t_write(fd, buf[off..].as_ptr(), buf.len() - off) };
        if n <= 0 {
            return false;
        }
        off += n as usize;
    }
    true
}

/// Decode the 9P `size[4]` little-endian prefix and validate it.
///
/// Returns the TOTAL frame length (header included), or None if the peer
/// claimed a size that cannot be a 9P message. Refusing here is what keeps a
/// bad length from becoming a giant allocation or an inward-handed lie.
fn frame_len(hdr: &[u8; 4]) -> Option<u32> {
    let size = u32::from_le_bytes(*hdr);
    if !(MSG_MIN..=MSG_MAX).contains(&size) {
        return None;
    }
    Some(size)
}

/// Read one complete 9P message from `src` into `buf` (header included).
///
/// Returns false at end of channel or on a length the peer had no business
/// claiming. Refusing the length HERE is what stops it becoming a giant
/// allocation or a lie handed to the next layer.
fn read_frame(src: i64, buf: &mut Vec<u8>) -> bool {
    let mut hdr = [0u8; 4];
    if !read_exact(src, &mut hdr) {
        return false;
    }
    let size = match frame_len(&hdr) {
        Some(s) => s,
        None => {
            say!(
                "haul: refusing a frame claiming {} bytes (bound {})",
                u32::from_le_bytes(hdr),
                MSG_MAX
            );
            return false;
        }
    };
    buf.clear();
    buf.extend_from_slice(&hdr);
    buf.resize(size as usize, 0);
    read_exact(src, &mut buf[4..])
}

/// Everything the kernel->server pump needs. Passed by pointer through
/// `spawn_raw`'s argument rather than through statics: the Sealer is owned by
/// exactly one thread, and a static would have to be `static mut` to say so.
struct UpCtx {
    src: i64,
    dst: i64,
    sealer: Option<npxf::Sealer>,
}

/// Everything the server->kernel pump needs.
struct DownCtx {
    src: i64,
    dst: i64,
    opener: Option<npxf::Opener>,
}

/// Record which direction ended, and exit the thread.
///
/// A PUMP CLOSES NOTHING. The obvious shape -- have the dying pump close the
/// kernel's write end, so a session waiting on a reply sees EOF instead of
/// parking forever -- puts one thread's `close` against the other thread's
/// in-flight `write` on the SAME fd, and the fd number can be recycled between
/// the two. Electing a single closer by CAS removes the double close but not
/// that race.
///
/// Instead the main thread observes STOPPED and lets the PROCESS exit, which
/// closes every fd at once, from outside both pumps. The kernel sees the same
/// EOF, bounded by the 200 ms poll, and no fd is ever closed underneath a
/// writer. Exiting is correct rather than merely convenient: haul IS the
/// transport, so once either direction is dead the mount is dead too.
fn finish(which: u32) -> ! {
    let _ = STOPPED.compare_exchange(STOP_NONE, which, Ordering::AcqRel, Ordering::Acquire);
    unsafe { libthyla_rs::t_thread_exit() };
}

/// kernel -> server. Reads T-messages the kernel wrote into its pipe and puts
/// them on the wire -- as-is when plain, or as one AEAD record each when the
/// channel is secured.
extern "C" fn pump_up(arg: u64) {
    // SAFETY: `arg` is the leaked Box handed to spawn_raw below, and this
    // thread is its only reader for the rest of the process's life.
    let ctx = unsafe { &mut *(arg as *mut UpCtx) };
    let mut msg: Vec<u8> = Vec::new();
    let mut rec: Vec<u8> = Vec::new();

    while read_frame(ctx.src, &mut msg) {
        let ok = match ctx.sealer.as_mut() {
            None => write_exact(ctx.dst, &msg),
            Some(s) => match s.seal(&msg, &mut rec) {
                Ok(()) => write_exact(ctx.dst, &rec),
                Err(e) => {
                    say!("haul: sealing a {}-byte message failed ({:?})", msg.len(), e);
                    false
                }
            },
        };
        if !ok {
            break;
        }
    }
    finish(STOP_UP);
}

/// server -> kernel. Takes R-messages off the wire and writes them into the
/// kernel's pipe, decrypting first when the channel is secured.
extern "C" fn pump_down(arg: u64) {
    // SAFETY: as pump_up.
    let ctx = unsafe { &mut *(arg as *mut DownCtx) };
    let mut buf: Vec<u8> = Vec::new();

    loop {
        let ok = match ctx.opener.as_mut() {
            // Plain: the stream IS 9P, so the same framed relay as the other
            // direction.
            None => read_frame(ctx.src, &mut buf) && write_exact(ctx.dst, &buf),
            Some(o) => match read_record(ctx.src, o, &mut buf) {
                RecordIn::Message(n) => write_exact(ctx.dst, &buf[..n]),
                RecordIn::Ended => false,
            },
        };
        if !ok {
            break;
        }
    }
    finish(STOP_DOWN);
}

enum RecordIn {
    /// `buf[..n]` holds one decrypted 9P message.
    Message(usize),
    /// Clean EOF, a refused length, or a failed tag -- all terminal.
    Ended,
}

/// Read one AEAD record and decrypt it in place.
///
/// The decrypted payload must be a whole 9P message whose own `size[4]` equals
/// the record's length -- npxf's server enforces exactly that on its side, and
/// we enforce it here because the kernel reads a BYTE STREAM: a payload whose
/// declared size disagreed with its length would silently desync the pipe
/// rather than fail.
fn read_record(src: i64, o: &mut npxf::Opener, buf: &mut Vec<u8>) -> RecordIn {
    let mut hdr = [0u8; npxf::RECORD_HDR];
    if !read_exact(src, &mut hdr) {
        return RecordIn::Ended;
    }
    let body = match o.body_len(&hdr) {
        Ok(n) => n,
        Err(e) => {
            say!(
                "haul: refusing a record claiming {} bytes ({:?})",
                u32::from_le_bytes(hdr),
                e
            );
            return RecordIn::Ended;
        }
    };

    buf.clear();
    buf.resize(body, 0);
    if !read_exact(src, buf) {
        return RecordIn::Ended;
    }

    let n = match o.open(&hdr, buf) {
        Ok(pt) => pt.len(),
        Err(e) => {
            // A tag failure is tampering, reordering or truncation. The session
            // is already poisoned by `open`; say so plainly and end.
            say!("haul: record authentication failed ({:?}) -- the channel is over", e);
            return RecordIn::Ended;
        }
    };

    if n < MSG_MIN as usize || u32::from_le_bytes([buf[0], buf[1], buf[2], buf[3]]) as usize != n {
        say!("haul: a record's 9P size field disagrees with the record length");
        return RecordIn::Ended;
    }
    RecordIn::Message(n)
}

/// Spawn one pump, handing it ownership of `ctx`.
///
/// The Box is leaked deliberately: the pump runs for the process's life and
/// there is no join, so nothing would ever reclaim it. The pointer is the
/// thread's argument.
fn spawn_pump<T>(entry: extern "C" fn(u64), ctx: T) -> Result<(), &'static str> {
    let stack = unsafe { t_burrow_attach(PUMP_STACK) };
    if stack < 0 {
        return Err("pump stack");
    }
    // AAPCS64 wants the stack TOP 16-aligned; the burrow base is page-aligned
    // and the size is a page multiple, so base + size is too.
    let sp = (stack as u64) + PUMP_STACK;
    let arg = alloc::boxed::Box::into_raw(alloc::boxed::Box::new(ctx)) as u64;
    match unsafe { thread::spawn_raw(entry as *const () as u64, sp, arg, 0) } {
        Ok(_) => Ok(()),
        Err(_) => {
            // The thread never started, so nothing else can reach the Box --
            // reclaim it rather than leaking on the error path.
            drop(unsafe { alloc::boxed::Box::from_raw(arg as *mut T) });
            Err("pump spawn")
        }
    }
}

const USAGE: &str = "\
usage: haul [-a aname] [-t file | --token-env VAR] host!port mountpoint [cmd ...]
  Mount a remote 9P2000.L tree served over TCP.

  With a command, haul mounts, runs it WITH THE TREE VISIBLE, and exits with
  its status. Without one it parks, holding the mount, until the peer hangs up.
  A mount lands in the calling Proc's namespace only, and a child inherits it --
  so a backgrounded `haul ... &` is NOT visible to the shell that started it.
  The command is resolved from the namespace root, with no PATH search: write
  /bin/cat, not cat.

  -a aname        the tree to attach (default \"/\")
  -t file         shared token file -- enables npxf's encrypted channel
  --token-env VAR read the token from /env/VAR instead
  -v              report each step (dial, handshake, attach, mount)
  --help          show this help

The address takes the Plan 9 form host!port, or host:port. With no token the
connection is PLAIN 9P; npxf servers always require one.

Note: ut lexes a bare `!`, so QUOTE the address at an interactive prompt.

Example:
  haul -t /cfg/npxf.token '10.0.2.100!7820' /n/host
";

struct Parsed {
    addr: String,
    mountpoint: String,
    aname: String,
    /// None = plain 9P; Some = run npxf's handshake first.
    token: Option<Vec<u8>>,
    /// Optional command to run WITH the mount visible. Empty = park instead.
    cmd: Vec<String>,
}

/// Read a token from a file, dropping ONE trailing newline.
///
/// npxf does the same on its side, and it has to: a token file written by any
/// ordinary editor ends in a newline, and a byte of difference is a different
/// pre-shared key and a handshake that fails with no clue why.
fn read_token_file(path: &str) -> Result<Vec<u8>, &'static str> {
    let mut f = libthyla_rs::fs::File::open(path).map_err(|_| "cannot open the token file")?;
    let mut buf: Vec<u8> = Vec::new();
    f.read_to_end(&mut buf).map_err(|_| "cannot read the token file")?;
    if buf.last() == Some(&b'\n') {
        buf.pop();
    }
    if buf.is_empty() {
        return Err("the token file is empty");
    }
    Ok(buf)
}

fn parse_args(args: Args) -> Result<Parsed, &'static str> {
    let mut aname = String::from("/");
    let mut token: Option<Vec<u8>> = None;
    let mut positional: Vec<String> = Vec::new();
    let mut i = 1usize; // argv[0] is the program name
    while let Some(a) = args.get(i) {
        if a == b"-a" {
            i += 1;
            match args.get_str(i) {
                Some(v) => aname = String::from(v),
                None => return Err("-a wants a tree name"),
            }
        } else if a == b"-t" || a == b"--token-file" {
            i += 1;
            match args.get_str(i) {
                Some(v) => token = Some(read_token_file(v)?),
                None => return Err("-t wants a file"),
            }
        } else if a == b"--token-env" {
            i += 1;
            match args.get_str(i) {
                Some(v) => match env::var(v) {
                    Some(val) if !val.is_empty() => token = Some(val.into_bytes()),
                    _ => return Err("that environment variable is unset or empty"),
                },
                None => return Err("--token-env wants a variable name"),
            }
        } else if a == b"-v" || a == b"--verbose" {
            VERBOSE.store(1, Ordering::Relaxed);
        } else if a == b"-h" || a == b"--help" {
            let _ = t_putstr(USAGE);
            return Err("");
        } else if a.first() == Some(&b'-') && a.len() > 1 {
            return Err("unknown option");
        } else {
            match args.get_str(i) {
                Some(v) => positional.push(String::from(v)),
                None => return Err("argument is not UTF-8"),
            }
        }
        i += 1;
    }
    if positional.len() < 2 {
        let _ = t_putstr(USAGE);
        return Err("");
    }
    Ok(Parsed {
        addr: positional[0].clone(),
        mountpoint: positional[1].clone(),
        aname,
        token,
        cmd: positional[2..].to_vec(),
    })
}

/// Run npxf's three flights on the connected socket and return the live
/// channel.
///
/// FAILS CLOSED ON THE CSPRNG. The ephemeral scalar is the whole of the
/// session's forward secrecy; there is no weaker source to fall back to, so a
/// kernel that will not give us entropy ends the mount here rather than
/// producing a channel that merely looks encrypted.
fn npxf_handshake(fd: i64, token: &[u8]) -> Result<npxf::Session, &'static str> {
    let mut eph = [0u8; 32];
    let got = libthyla_rs::rand::fill_bytes(&mut eph);
    if got.is_err() {
        return Err("no CSPRNG (needs CAP_CSPRNG_READ) -- refusing to handshake");
    }
    step!("entropy for the ephemeral: ok");

    let (client, msg1) = npxf::Client::start(token, eph).map_err(|_| "the token is empty")?;
    eph.zeroize();

    if !write_exact(fd, &msg1) {
        return Err("handshake: the connection closed while sending our opening flight");
    }
    step!("sent flight 1 ({} bytes)", msg1.len());

    let mut msg2 = [0u8; npxf::MSG2_LEN];
    if !read_exact(fd, &mut msg2) {
        return Err("handshake: the server closed without replying (wrong token, or not npxf)");
    }
    step!("got flight 2 ({} bytes)", msg2.len());

    let (mut session, msg3) = client.finish(&msg2).map_err(|e| match e {
        npxf::Error::ServerAuth => {
            "handshake: server authentication failed -- token mismatch, or intercepted"
        }
        npxf::Error::SmallOrderKey => "handshake: the server sent a small-order public key",
        _ => "handshake: refused",
    })?;

    if !write_exact(fd, &msg3) {
        return Err("handshake: the connection closed while confirming");
    }
    step!("server authenticated, channel up");

    // Hold both directions to the same ceiling the plain path uses, so a server
    // cannot make us allocate npxf's full 8 MiB record just by claiming it.
    session.send.set_max_payload(MSG_MAX as usize);
    session.recv.set_max_payload(MSG_MAX as usize);
    Ok(session)
}

fn run(argv: Args) -> Result<(), &'static str> {
    let args = parse_args(argv)?;

    let (host, port) = haul::addr::split_dial(&args.addr)
        .ok_or("address needs a host and a port (host!port, or host:port)")?;
    let ip = Ipv4Addr::parse(host).map_err(|_| "the host is not a dotted-quad IPv4 address")?;
    let port = haul::addr::parse_port(port).ok_or("the port must be 1..=65535")?;
    let addr = SocketAddrV4::new(ip, port);
    step!("dialing {}", addr);
    let stream = TcpStream::connect(addr).map_err(|_| "connect")?;
    step!("connected");
    // The pumps outlive this scope and address the connection by fd, so the
    // TcpStream must NOT drop (its Drop closes ctl + data, tearing the
    // connection down under them). Leaked deliberately: haul lives for the
    // mount's lifetime, so the connection's lifetime IS the process's.
    let tcp_fd = stream.as_raw_fd() as i64;
    core::mem::forget(stream);

    // THE HANDSHAKE RUNS BEFORE THE PUMPS, and it must: it is a strictly
    // ordered three-flight exchange on the raw socket, so a pump concurrently
    // reading that socket would steal the server's reply. Once it returns, the
    // socket carries records only, and the pumps own it.
    let session = match args.token.as_deref() {
        Some(t) => Some(npxf_handshake(tcp_fd, t)?),
        None => None,
    };
    let (sealer, opener) = match session {
        Some(s) => (Some(s.send), Some(s.recv)),
        None => (None, None),
    };

    // Two half-duplex pipes: c2s carries T-messages, s2c carries R-messages.
    let (c2s_rd, c2s_wr) = unsafe { t_pipe() };
    let (s2c_rd, s2c_wr) = unsafe { t_pipe() };
    if c2s_rd < 0 || c2s_wr < 0 || s2c_rd < 0 || s2c_wr < 0 {
        return Err("pipe pair");
    }

    // BOTH PUMPS BEFORE THE ATTACH. SYS_ATTACH_9P drives Tversion + Tattach
    // synchronously; with no pump running, the kernel would wait for an
    // Rversion nothing can deliver and the mount would hang rather than fail.
    spawn_pump(
        pump_up,
        UpCtx {
            src: c2s_rd,
            dst: tcp_fd,
            sealer,
        },
    )?;
    spawn_pump(
        pump_down,
        DownCtx {
            src: tcp_fd,
            dst: s2c_wr,
            opener,
        },
    )?;
    step!("pumps up; attaching (Tversion + Tattach run inside the syscall)");

    // The attach takes its own refs on both transport Spoors, so our copies of
    // the CLIENT ends close immediately after -- the session keeps the channel,
    // not these fds. (The SERVER ends stay open: they are the pumps'.)
    let root = unsafe {
        t_attach_9p(
            c2s_wr,
            s2c_rd,
            args.aname.as_ptr(),
            args.aname.len(),
            0,
        )
    };
    let _ = unsafe { t_close(c2s_wr) };
    let _ = unsafe { t_close(s2c_rd) };
    if root < 0 {
        // The pumps have the diagnosis: a server that hung up mid-handshake
        // stops one of them, and which one says whether we failed to send or
        // failed to hear back.
        return Err(match STOPPED.load(Ordering::Acquire) {
            STOP_UP => "attach (the connection closed while sending)",
            STOP_DOWN => "attach (the server closed without replying)",
            _ => "attach (9P handshake refused)",
        });
    }

    step!("attached; mounting at {}", args.mountpoint);
    let rc = unsafe {
        t_mount(
            args.mountpoint.as_ptr(),
            args.mountpoint.len(),
            root,
            T_MREPL,
        )
    };
    let _ = unsafe { t_close(root) };
    if rc < 0 {
        return Err("mount");
    }

    // Under -v, prove the mount from INSIDE this Proc before anyone else tries
    // to use it. A successful t_mount says the entry went into our table; it
    // does not say a walk crosses into the remote tree. Listing here separates
    // "the mount is wrong" from "the caller cannot see it", which are the two
    // failures that otherwise both present as `no such file or namespace entry`.
    if VERBOSE.load(Ordering::Relaxed) != 0 {
        match libthyla_rs::fs::read_dir(args.mountpoint.as_str()) {
            Ok(rd) => {
                let mut n = 0usize;
                let mut first = String::new();
                for e in rd.flatten() {
                    if n == 0 {
                        first = String::from(e.file_name());
                    }
                    n += 1;
                }
                step!("mount check: {} entr(y/ies) here, first {:?}", n, first);
            }
            Err(_) => step!("mount check: CANNOT read {} -- the mount did not take", args.mountpoint),
        }
    }

    // Name the channel, always. Which mode is live is exactly the thing a
    // reader must never have to infer from the absence of a flag.
    say!(
        "haul: {} mounted at {} (aname {}, {})",
        args.addr,
        args.mountpoint,
        args.aname,
        if args.token.is_some() {
            "npxf encrypted"
        } else {
            "PLAIN 9P"
        }
    );

    // WITH A COMMAND: run it here, where the mount exists.
    //
    // A mount lands in the CALLING Proc's Territory and nowhere else (I-1), and
    // a child inherits its parent's namespace at spawn -- never the reverse. So
    // `haul ... &` from a shell mounts into haul's OWN namespace and the
    // shell sees nothing; measured, on the first working channel:
    //   cat: /home/cora/host/hello.txt: no such file or namespace entry
    // while haul sat happily mounted. This is the Plan 9 answer -- rfork,
    // mount, exec -- and the child sees the tree because it is downstream of the
    // mount rather than beside it. Delivering a mount to an EXISTING shell needs
    // /srv (post the connection, let the shell mount it); that is a separate
    // chunk and a design question, recorded in docs/HAUL-DESIGN.md.
    if !args.cmd.is_empty() {
        let mut c = libthyla_rs::process::Command::new(args.cmd[0].clone());
        c.args(args.cmd[1..].iter().cloned());
        let status = match c.spawn() {
            Ok(mut child) => child.wait().map_err(|_| "waiting for the command")?,
            Err(_) => return Err("could not run the command"),
        };
        // The transport dies with us, which is correct: the command has run, so
        // the tree it needed is no longer needed.
        return if status.success() {
            Ok(())
        } else {
            Err("the command exited non-zero")
        };
    }

    // WITHOUT ONE: the mount lives exactly as long as this Proc does -- the
    // pumps ARE the transport, so exiting would tear the session down under
    // whoever is walking the tree. Park until a pump reports the channel ended.
    loop {
        if STOPPED.load(Ordering::Acquire) != STOP_NONE {
            say!("haul: {} closed the connection -- the mount is dead", args.addr);
            return Ok(());
        }
        let _ = libthyla_rs::time::sleep(libthyla_rs::time::Duration::from_millis(200));
    }
}

#[no_mangle]
pub extern "C" fn rs_main() -> i64 {
    match run(env::args()) {
        Ok(()) => 0,
        // The empty reason is --help / usage: already printed, and a second
        // line naming it as a failure would be wrong.
        Err("") => 2,
        Err(why) => {
            say!("haul: {}", why);
            1
        }
    }
}
