// haul -- mount a remote 9P2000.L tree served over TCP.
//
// A thylacine hauled a kill back to cover to eat it. This drags a tree from
// outside the machine into the local namespace, and the pages it yields are
// cached by the Larder (the guest-side FS cache, I-38).
//
// Named per CLAUDE.md "Thematic naming", operator-ratified 2026-09-09. It was
// `forage` for one day, which collided with `tools/forage.sh`, the build-input
// collector -- same metaphor, different layer, and the two are confusable in
// prose even though they never co-occur on a command line. `mount` and `srv`
// are the Plan 9 words; `quarry`, `prowl` and `larder` are taken.
//
//   haul [-a aname] host!port mountpoint
//   haul -t /cfg/npxf.token '10.0.2.2!5640' /n/host
//
// WHY A USERSPACE SHIM AT ALL. The kernel's 9P client speaks 9P2000.L over a
// BYTE PIPE, not over TCP: `9p_spoor_transport` moves messages across a pair of
// Spoors, and there is no in-kernel socket transport (there is deliberately no
// TCP in the kernel at all -- netd owns the stack). SYS_ATTACH_9P's own doc
// names the way across:
//
//     "For half-duplex (Plan 9 pipes from SYS_PIPE), userspace creates two
//      pipe pairs and passes the matching write-end and read-end."
//
// So haul holds the SERVER ends of two pipes, hands the CLIENT ends to
// SYS_ATTACH_9P, and shuttles bytes between those and the TCP connection. The
// kernel believes it is talking to a local 9P server; the server believes it is
// talking to a local 9P client. `usr/viv` already drives this exact attach for
// the container diorama -- the pattern is live, not new.
//
// THE ORDERING THAT MATTERS. SYS_ATTACH_9P performs Tversion + Tattach
// SYNCHRONOUSLY inside the syscall, so it blocks until replies arrive. Nothing
// can reply unless the pumps are already running. Hence: spawn both pump
// threads FIRST, then attach from the main thread. Reversing those two
// deadlocks -- the kernel waits for an Rversion that only a thread that has not
// been spawned could deliver.
//
// FRAMED, NOT BLIND. A plain byte splice would be correct for the plaintext
// case (9P over TCP is just the stream). The pump parses the 9P `size[4]`
// prefix anyway, for two reasons: the npxf secure channel seals ONE 9P MESSAGE
// PER AEAD RECORD and so needs message boundaries, and framing lets a hostile
// or confused peer's absurd length claim be refused HERE rather than handed
// inward. That is what made the npxf layer a swap of the pump's read/write pair
// rather than a rewrite of it.
//
// THE SECURE CHANNEL (`-t` / `--token-env`). With a token, haul runs npxf's
// three-flight handshake on the socket before anything else and then carries
// every 9P message as one AEAD record. The protocol lives in `npxf.rs` -- pure,
// syscall-free, and pinned byte for byte to vectors generated by npxf's own
// implementation. Only the I/O is here.
//
// THE EPHEMERAL COMES FROM THE KERNEL CSPRNG, OR THE MOUNT FAILS. Forward
// secrecy rests entirely on that scalar being unpredictable, so there is no
// fallback source and no "degraded" mode: SYS_GETRANDOM (CAP_CSPRNG_READ) works
// or haul refuses to connect.

#![no_std]
#![no_main]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use core::sync::atomic::{AtomicU32, Ordering};

use haul::{cmdline, npxf};
use libthyla_rs::env::{self, Args};
use zeroize::{Zeroize, Zeroizing};
use libthyla_rs::io::Read;
use libthyla_rs::net::{Ipv4Addr, SocketAddrV4, TcpStream};
use libthyla_rs::thread;
use libthyla_rs::{
    t_attach_9p, t_burrow_attach, t_close, t_mount, t_pipe, t_putstr, T_MREPL,
};

#[global_allocator]
static GLOBAL_ALLOCATOR: libthyla_rs::alloc::ThylaAlloc = libthyla_rs::alloc::ThylaAlloc;

macro_rules! say {
    ($($a:tt)*) => {{
        let mut s = alloc::format!($($a)*);
        s.push('\n');
        let _ = libthyla_rs::t_putstr(&s);
    }};
}

/// Progress, under `-v`.
///
/// Not debug scaffolding: every step below can BLOCK -- the dial, the
/// handshake's two reads, and the attach (which drives Tversion + Tattach
/// synchronously inside the syscall). A haul that is merely slow and a haul
/// that is wedged look identical without this, which is exactly the state the
/// first guest run left us in: ninety seconds of silence and no way to say
/// which syscall owned them.
static VERBOSE: AtomicU32 = AtomicU32::new(0);

macro_rules! step {
    ($($a:tt)*) => {{
        if VERBOSE.load(Ordering::Relaxed) != 0 {
            let mut s = alloc::string::String::from("haul: .. ");
            s.push_str(&alloc::format!($($a)*));
            s.push('\n');
            let _ = libthyla_rs::t_putstr(&s);
        }
    }};
}

/// The largest 9P message haul will relay in either direction.
///
/// A 9P message is `size[4]` INCLUDING those four bytes, so this bounds the
/// whole frame. It is a shim-side ceiling, not the negotiated msize: haul does
/// not parse Tversion (it is a transport, not a client), so it cannot know what
/// the two ends agreed on.
///
/// The number is chosen against what the two ends CAN agree on. This transport
/// is the pipe attach, whose msize is the fixed `SYS_ATTACH_DEFAULT_MSIZE`
/// (4 KiB, kernel/syscall.c) -- the kernel proposes it, caps its own recv at it,
/// and there is no path by which a larger frame is legitimate here. 64 KiB
/// therefore leaves sixteen-fold headroom for a future msize bump while keeping
/// the worst case a hostile server can drive to two 64 KiB buffers, one per
/// pump, against `INITIAL_HEAP_SIZE` (4 MiB, and NOT growable).
///
/// It was 1 MiB, which was described as "far below a length a hostile peer could
/// use to make us allocate the heap". Two of those is a quarter of the heap, and
/// on exhaustion the panic handler calls `t_exits(1)` -- so a bound written to
/// prevent a denial of service was set where it could deliver one.
const MSG_MAX: u32 = 64 * 1024;

/// A 9P message is at minimum `size[4] type[1] tag[2]`. npxf's server refuses
/// anything shorter as a runt; matching it here means a malformed frame dies at
/// the transport instead of being handed to a parser on either side.
const MSG_MIN: u32 = 7;

/// Per-pump stack. One page is ample -- a pump's frame is a buffer pointer and
/// a few counters; the message buffer itself is heap.
const PUMP_STACK: u64 = 64 * 1024;

/// Set by whichever pump stops first, so the survivor's diagnosis names the
/// side that actually ended rather than the side that noticed, and so the main
/// thread learns the transport is over.
static STOPPED: AtomicU32 = AtomicU32::new(0);

const STOP_NONE: u32 = 0;
const STOP_UP: u32 = 1; // kernel -> server direction ended
const STOP_DOWN: u32 = 2; // server -> kernel direction ended

/// Read exactly `buf.len()` bytes, or report short. A single `read` on either a
/// pipe or a TCP stream may return less than asked for, and a 9P frame that is
/// split across two reads is the ordinary case, not the exceptional one.
fn read_exact(fd: i64, buf: &mut [u8]) -> bool {
    let mut off = 0usize;
    while off < buf.len() {
        let n = unsafe { libthyla_rs::t_read(fd, buf[off..].as_mut_ptr(), buf.len() - off) };
        if n <= 0 {
            return false; // EOF or error: the caller treats both as "channel over"
        }
        off += n as usize;
    }
    true
}

/// How long the handshake will wait for the server's flight, matching the
/// bracket npxf puts around its own (`kHandshakeTimeoutMs`, channel.hpp).
///
/// Without it, a peer that completes the TCP handshake and then says nothing
/// holds haul in a read forever, BEFORE authentication -- so anything that can
/// accept a connection can pin the process, with no token and no reply. The
/// verbose trace stops at "sent flight 1", which is a good description of the
/// symptom and no help at all against it.
const HANDSHAKE_MS: i32 = 15_000;

/// How long a stalled write waits for the far side to make room before the
/// channel is declared dead. A healthy TCP transmit buffer drains in
/// milliseconds; a socket that is actually gone never becomes writable at all,
/// so the only thing this bound has to separate is "slow" from "never" -- and
/// erring long is right, because a stalled remote filesystem should block, not
/// tear the mount down.
const WRITE_STALL_MS: i32 = 30_000;

/// THE READINESS FD IS NOT THE DATA FD, and using the wrong one is silent.
///
/// A netd connection is two files. `data` carries bytes; `ready` carries
/// readiness, and only `ready` is marked QTPOLL (`usr/netd/src/server.rs`
/// `P9_QTFILE | P9_QTPOLL` -- the `data` file is not). `dev9p_poll`'s QTPOLL
/// gate deliberately FAILS SAFE for everything else: an unmarked file is
/// "POSIX always-ready", returning the requested bits immediately rather than
/// probing (`kernel/dev9p_poll.c`).
///
/// So polling the DATA fd does not fail -- it succeeds, instantly, always, and
/// says nothing. A POLLOUT wait on it becomes a busy spin; a POLLIN wait before
/// a blocking read becomes a no-op that leaves the read unbounded. Both are
/// bugs that look exactly like working code, which is why this type exists
/// instead of an `i64` parameter that either fd would satisfy.
///
/// `Ready(fd) == the fd to poll`; for a pipe that is the pipe itself, whose
/// POLLOUT is real (`kernel/pipe.c` sets it on `count < PIPE_BUF_SIZE`).
#[derive(Copy, Clone)]
struct Ready(i64);

/// Wait for `events` on a readiness fd, up to `ms`. False on timeout or error.
fn wait_ready(r: Ready, events: i16, ms: i32) -> bool {
    let mut pfd = libthyla_rs::TPollFd { fd: r.0 as i32, events, revents: 0 };
    let n = unsafe { libthyla_rs::t_poll(&mut pfd, 1, ms) };
    n > 0 && pfd.revents & events != 0
}

/// `read_exact` under a TOTAL deadline, for the pre-authentication window where
/// a silent peer must not be able to park us.
///
/// The bound is for the whole read, not for each wait. A per-wait bound was the
/// first shape here, defended with "the flights are 64 bytes, so there is
/// nothing to dribble" -- and 64 bytes is exactly 64 dribbles: one byte every
/// 14 seconds would have stretched a 15-second bracket to sixteen minutes, per
/// connection, before authentication. A peer that is making progress is not
/// thereby entitled to unlimited time.
fn read_exact_before(fd: i64, r: Ready, buf: &mut [u8], ms: i32) -> bool {
    let started = libthyla_rs::time::Instant::now();
    let mut off = 0usize;
    while off < buf.len() {
        let spent = started.elapsed().as_millis() as i64;
        let left = ms as i64 - spent;
        if left <= 0 {
            return false;
        }
        if !wait_ready(r, libthyla_rs::T_POLLIN, left as i32) {
            return false;
        }
        let n = unsafe { libthyla_rs::t_read(fd, buf[off..].as_mut_ptr(), buf.len() - off) };
        if n <= 0 {
            return false;
        }
        off += n as usize;
    }
    true
}

/// Write all of `buf`, treating a zero-byte write as back-pressure rather than
/// as failure.
///
/// A /net data fd does NOT block. netd's TCP send is
/// `send_slice(data).unwrap_or(0)` (usr/netd/src/server.rs), and dev9p hands
/// that count straight back to EL0 (`dev9p_write` returns `accepted`,
/// kernel/dev9p.c), so a full transmit buffer makes `t_write` return 0 with the
/// connection perfectly healthy. The obvious `n <= 0` idiom reads that as the
/// end of the channel and tears the mount down under nothing worse than a busy
/// link -- and can do it MID-RECORD, leaving a truncated AEAD frame on the wire
/// for the peer to reject.
///
/// The zero is ambiguous on its own: `unwrap_or(0)` swallows the error a dead
/// socket returns too, so the count alone cannot separate "full" from "gone".
/// Readiness can -- but only the RIGHT fd's. POLLOUT on the `ready` sibling is
/// netd's `can_send()`, which is false for a dead socket and true once the send
/// window has room; POLLOUT on `data` is the always-ready answer of a file that
/// carries no readiness at all. See `Ready`.
fn write_exact(fd: i64, r: Ready, buf: &[u8]) -> bool {
    let mut off = 0usize;
    // Bounds the CUMULATIVE time spent making no progress, reset by any byte
    // written. A per-wait bound would not terminate if readiness kept firing
    // while the write kept returning 0 -- POLLOUT is netd's `can_send()`
    // sampled at poll time, and a window that opens and closes again between
    // the poll and the write is a spurious wakeup, not a contract violation.
    // Without this the loop would be bounded only by the peer's good behaviour.
    let mut stalled_since: Option<libthyla_rs::time::Instant> = None;
    while off < buf.len() {
        let n = unsafe { libthyla_rs::t_write(fd, buf[off..].as_ptr(), buf.len() - off) };
        if n < 0 {
            return false;
        }
        if n == 0 {
            let since = *stalled_since.get_or_insert_with(libthyla_rs::time::Instant::now);
            let spent = since.elapsed().as_millis() as i64;
            let left = WRITE_STALL_MS as i64 - spent;
            if left <= 0 || !wait_ready(r, libthyla_rs::T_POLLOUT, left as i32) {
                say!("haul: write stalled with {} bytes left", buf.len() - off);
                return false;
            }
            continue;
        }
        stalled_since = None;
        off += n as usize;
    }
    true
}

/// Decode the 9P `size[4]` little-endian prefix and validate it.
///
/// Returns the TOTAL frame length (header included), or None if the peer
/// claimed a size that cannot be a 9P message. Refusing here is what keeps a
/// bad length from becoming a giant allocation or an inward-handed lie.
fn frame_len(hdr: &[u8; 4]) -> Option<u32> {
    let size = u32::from_le_bytes(*hdr);
    if !(MSG_MIN..=MSG_MAX).contains(&size) {
        return None;
    }
    Some(size)
}

/// Read one complete 9P message from `src` into `buf` (header included).
///
/// Returns false at end of channel or on a length the peer had no business
/// claiming. Refusing the length HERE is what stops it becoming a giant
/// allocation or a lie handed to the next layer.
fn read_frame(src: i64, buf: &mut Vec<u8>) -> bool {
    let mut hdr = [0u8; 4];
    if !read_exact(src, &mut hdr) {
        return false;
    }
    let size = match frame_len(&hdr) {
        Some(s) => s,
        None => {
            say!(
                "haul: refusing a frame claiming {} bytes (bound {})",
                u32::from_le_bytes(hdr),
                MSG_MAX
            );
            return false;
        }
    };
    buf.clear();
    buf.extend_from_slice(&hdr);
    buf.resize(size as usize, 0);
    read_exact(src, &mut buf[4..])
}

/// Everything the kernel->server pump needs. Passed by pointer through
/// `spawn_raw`'s argument rather than through statics: the Sealer is owned by
/// exactly one thread, and a static would have to be `static mut` to say so.
struct UpCtx {
    src: i64,
    dst: i64,
    /// Readiness for `dst`, which is the TCP connection -- so this is its
    /// `ready` sibling, never `dst` itself. See `Ready`.
    dst_ready: Ready,
    sealer: Option<npxf::Sealer>,
}

/// Everything the server->kernel pump needs.
struct DownCtx {
    src: i64,
    dst: i64,
    /// Readiness for `dst`, which is a pipe -- and a pipe's own fd carries real
    /// POLLOUT (`kernel/pipe.c`), so here it IS `dst`.
    dst_ready: Ready,
    opener: Option<npxf::Opener>,
}

/// Record which direction ended, and exit the thread.
///
/// A PUMP CLOSES NOTHING. The obvious shape -- have the dying pump close the
/// kernel's write end, so a session waiting on a reply sees EOF instead of
/// parking forever -- puts one thread's `close` against the other thread's
/// in-flight `write` on the SAME fd, and the fd number can be recycled between
/// the two. Electing a single closer by CAS removes the double close but not
/// that race.
///
/// Instead the main thread observes STOPPED and lets the PROCESS exit, which
/// closes every fd at once, from outside both pumps. The kernel sees the same
/// EOF, bounded by the 200 ms poll, and no fd is ever closed underneath a
/// writer. Exiting is correct rather than merely convenient: haul IS the
/// transport, so once either direction is dead the mount is dead too.
fn finish(which: u32) -> ! {
    let _ = STOPPED.compare_exchange(STOP_NONE, which, Ordering::AcqRel, Ordering::Acquire);
    unsafe { libthyla_rs::t_thread_exit() };
}

/// kernel -> server. Reads T-messages the kernel wrote into its pipe and puts
/// them on the wire -- as-is when plain, or as one AEAD record each when the
/// channel is secured.
extern "C" fn pump_up(arg: u64) {
    // SAFETY: `arg` is the leaked Box handed to spawn_raw below, and this
    // thread is its only reader for the rest of the process's life.
    let ctx = unsafe { &mut *(arg as *mut UpCtx) };
    let mut msg: Vec<u8> = Vec::new();
    let mut rec: Vec<u8> = Vec::new();

    while read_frame(ctx.src, &mut msg) {
        let ok = match ctx.sealer.as_mut() {
            None => write_exact(ctx.dst, ctx.dst_ready, &msg),
            Some(s) => match s.seal(&msg, &mut rec) {
                Ok(()) => write_exact(ctx.dst, ctx.dst_ready, &rec),
                Err(e) => {
                    say!("haul: sealing a {}-byte message failed ({:?})", msg.len(), e);
                    false
                }
            },
        };
        if !ok {
            break;
        }
    }
    finish(STOP_UP);
}

/// server -> kernel. Takes R-messages off the wire and writes them into the
/// kernel's pipe, decrypting first when the channel is secured.
extern "C" fn pump_down(arg: u64) {
    // SAFETY: as pump_up.
    let ctx = unsafe { &mut *(arg as *mut DownCtx) };
    let mut buf: Vec<u8> = Vec::new();

    loop {
        let ok = match ctx.opener.as_mut() {
            // Plain: the stream IS 9P, so the same framed relay as the other
            // direction.
            None => read_frame(ctx.src, &mut buf) && write_exact(ctx.dst, ctx.dst_ready, &buf),
            Some(o) => match read_record(ctx.src, o, &mut buf) {
                RecordIn::Message(n) => write_exact(ctx.dst, ctx.dst_ready, &buf[..n]),
                RecordIn::Ended => false,
            },
        };
        if !ok {
            break;
        }
    }
    finish(STOP_DOWN);
}

enum RecordIn {
    /// `buf[..n]` holds one decrypted 9P message.
    Message(usize),
    /// Clean EOF, a refused length, or a failed tag -- all terminal.
    Ended,
}

/// Read one AEAD record and decrypt it in place.
///
/// The decrypted payload must be a whole 9P message whose own `size[4]` equals
/// the record's length -- npxf's server enforces exactly that on its side, and
/// we enforce it here because the kernel reads a BYTE STREAM: a payload whose
/// declared size disagreed with its length would silently desync the pipe
/// rather than fail.
fn read_record(src: i64, o: &mut npxf::Opener, buf: &mut Vec<u8>) -> RecordIn {
    let mut hdr = [0u8; npxf::RECORD_HDR];
    if !read_exact(src, &mut hdr) {
        return RecordIn::Ended;
    }
    let body = match o.body_len(&hdr) {
        Ok(n) => n,
        Err(e) => {
            say!(
                "haul: refusing a record claiming {} bytes ({:?})",
                u32::from_le_bytes(hdr),
                e
            );
            return RecordIn::Ended;
        }
    };

    buf.clear();
    buf.resize(body, 0);
    if !read_exact(src, buf) {
        return RecordIn::Ended;
    }

    let n = match o.open(&hdr, buf) {
        Ok(pt) => pt.len(),
        Err(e) => {
            // A tag failure is tampering, reordering or truncation. The session
            // is already poisoned by `open`; say so plainly and end.
            say!("haul: record authentication failed ({:?}) -- the channel is over", e);
            return RecordIn::Ended;
        }
    };

    if n < MSG_MIN as usize || u32::from_le_bytes([buf[0], buf[1], buf[2], buf[3]]) as usize != n {
        say!("haul: a record's 9P size field disagrees with the record length");
        return RecordIn::Ended;
    }
    RecordIn::Message(n)
}

/// A pump context, bound to the one entry point allowed to receive it.
///
/// The binding is the whole point of the trait. `UpCtx` and `DownCtx` are
/// layout-identical -- two fds and an `Option` holding a key -- so handing
/// `pump_up` a `DownCtx` would compile, link and run, and would seal outgoing
/// records under the RECEIVE key. Nothing crashes; the peer simply rejects every
/// record, and the tag failure says nothing about why. Taking the entry point as
/// a separate argument made that swap a one-token edit away at both call sites;
/// making it an associated constant makes it unrepresentable.
trait Pump: Sized {
    const ENTRY: extern "C" fn(u64);
}

impl Pump for UpCtx {
    const ENTRY: extern "C" fn(u64) = pump_up;
}

impl Pump for DownCtx {
    const ENTRY: extern "C" fn(u64) = pump_down;
}

/// Spawn one pump, handing it ownership of `ctx`.
///
/// The Box is leaked deliberately: the pump runs for the process's life and
/// there is no join, so nothing would ever reclaim it. The pointer is the
/// thread's argument.
fn spawn_pump<T: Pump>(ctx: T) -> Result<(), &'static str> {
    let entry = T::ENTRY;
    let stack = unsafe { t_burrow_attach(PUMP_STACK) };
    if stack < 0 {
        return Err("pump stack");
    }
    // AAPCS64 wants the stack TOP 16-aligned; the burrow base is page-aligned
    // and the size is a page multiple, so base + size is too.
    let sp = (stack as u64) + PUMP_STACK;
    let arg = alloc::boxed::Box::into_raw(alloc::boxed::Box::new(ctx)) as u64;
    match unsafe { thread::spawn_raw(entry as *const () as u64, sp, arg, 0) } {
        Ok(_) => Ok(()),
        Err(_) => {
            // The thread never started, so nothing else can reach the Box --
            // reclaim it rather than leaking on the error path.
            drop(unsafe { alloc::boxed::Box::from_raw(arg as *mut T) });
            Err("pump spawn")
        }
    }
}

const USAGE: &str = "\
usage: haul [-a aname] [-t file | --token-env VAR] host!port mountpoint [cmd ...]
  Mount a remote 9P2000.L tree served over TCP.

  Without a command haul parks, holding the mount, until the peer hangs up.
  A mount lands in the calling Proc's namespace ONLY, so a backgrounded
  `haul ... &` is not visible to the shell that started it.

  With a command, haul mounts and then runs it -- but a spawned child is NOT
  currently seeing the mount, which is an open kernel bug and not a property of
  this tool. Until it is fixed, prefer the parking form. The command is resolved
  from the namespace root, with no PATH search: write /bin/cat, not cat.
  Everything after the command word is passed to it verbatim; `--` ends haul's
  own options early.

  -a aname        the tree to attach (default \"/\")
  -t file         shared token file -- enables npxf's encrypted channel
  --token-env VAR read the token from /env/VAR instead
  -v              report each step (dial, handshake, attach, mount)
  --help          show this help

The address takes the Plan 9 form host!port, or host:port. With no token the
connection is PLAIN 9P; npxf servers always require one.

Note: a LITERAL host!port is typeable as-is. A composed one is not --
$host!$port lexes as three tokens and ut glues words only with ~ and ^, so it
splits; single quotes suppress the expansion, so write \"$host:$port\" instead.

Example:
  haul -t /cfg/npxf.token '10.0.2.100!7820' /n/host
";

struct Parsed {
    addr: String,
    mountpoint: String,
    aname: String,
    /// None = plain 9P; Some = run npxf's handshake first.
    ///
    /// `Zeroizing` because this is the LONG-LIVED credential: unlike a session
    /// key, its compromise is not bounded by this connection. Every derived key
    /// in npxf.rs already wipes on drop; the token is the one secret that used
    /// to be left to a plain `Vec::drop`, which frees the pages without
    /// touching the bytes.
    token: Option<Zeroizing<Vec<u8>>>,
    /// Optional command to run WITH the mount visible. Empty = park instead.
    cmd: Vec<String>,
}

/// Read a token from a file, dropping ONE trailing newline.
///
/// npxf does the same on its side, and it has to: a token file written by any
/// ordinary editor ends in a newline, and a byte of difference is a different
/// pre-shared key and a handshake that fails with no clue why.
/// The largest token file this will read.
///
/// npxf reads into a `Bytes buf(4096)` and fails when `n == buf.size()`
/// (`read_token_file`, npxf src/npxf_main.cpp), so its largest ACCEPTED token is
/// 4095 bytes -- one less than the buffer, which is easy to read as 4096 and is
/// what the comment here used to claim. The difference is not academic: a
/// 4096-byte token file that haul accepts is refused by `npxf-server` reading
/// the same file through the same function, so the server does not start and the
/// guest sees only a refused connection.
///
/// A file bigger than this is a mistake anyway -- a key ring, a log, the wrong
/// path -- and refusing it beats reading it: an unbounded read on a path the
/// caller chose is a way to turn `-t /dev/zero` into an out-of-memory kill.
const TOKEN_FILE_MAX: usize = 4095;

/// The ENV source's cap is a different number for a different reason, and using
/// the file's here was simply borrowing the wrong constant. npxf's `--token-env`
/// is `getenv` + `strlen` with no cap at all, so parity is bounded not by npxf
/// but by the kernel: `ENV_VALUE_MAX` (4096) is the most a variable can hold, so
/// anything at or under it is a value npxf would have accepted.
const TOKEN_ENV_MAX: usize = 4096;

/// Read the token named by an environment variable WITHOUT going through
/// `env::var`.
///
/// `env::var` reads into a 4096-byte STACK ARRAY and copies the value out into a
/// String, leaving the array unwiped when it returns (`libthyla-rs/src/env.rs`).
/// So the token -- the long-lived credential, whose compromise is not bounded by
/// the session the way a derived key's is -- would sit in a dead stack frame for
/// the life of the process, which in the park form is the life of the machine.
/// Wrapping the RESULT in `Zeroizing` wipes the heap copy and says nothing about
/// the one left behind.
///
/// `/env/<NAME>` is a plain file on the per-Proc env device, so reading it here
/// costs nothing and removes that stack copy. It does NOT make `--token-env` a
/// wiped path, and the difference matters: the authoritative bytes live in the
/// kernel's Env entry for the life of the Proc, untouched by our `drop`, and
/// `env_clone_into` hands them to every child the command form spawns. npxf's
/// `getenv` has exactly the same exposure, so this is parity rather than a
/// weaker posture -- but `-t` remains the source to reach for when the token
/// must not outlive its use. The name guard mirrors `env::var`'s.
fn read_token_env(name: &str) -> Result<Zeroizing<Vec<u8>>, &'static str> {
    if name.is_empty() || name.contains('/') {
        return Err("that is not an environment variable name");
    }
    let mut path = String::from("/env/");
    path.push_str(name);
    // NOT trimmed, matching npxf: a variable holds exactly what someone set it
    // to, whereas a file conventionally ends with a newline nobody typed. See
    // npxf::trim_token_file.
    read_token_bytes(&path, TokenRead {
        trim: false,
        max: TOKEN_ENV_MAX,
        // /env is per-Proc and synthetic: devenv reports a FIXED `T_S_IFREG |
        // 0644` for every variable (kernel/devenv.c), and nothing consults it --
        // devenv_wstat is `return -1`, so `chmod 600` cannot even succeed. The
        // mode warning would therefore fire on EVERY --token-env run, saying
        // something false and prescribing something impossible. A warning that
        // always fires is a warning an operator learns to ignore, and this is
        // the only place haul warns about credential exposure at all -- so
        // leaving it on here would cost the warning its meaning on the -t path,
        // where the bits are real.
        warn_mode: false,
        open_msg: "that environment variable is not set",
        read_msg: "cannot read that environment variable",
        large_msg: "that environment variable is too large",
        empty_msg: "that environment variable is empty",
    })
}

fn read_token_file(path: &str) -> Result<Zeroizing<Vec<u8>>, &'static str> {
    read_token_bytes(path, TokenRead {
        trim: true,
        max: TOKEN_FILE_MAX,
        warn_mode: true,
        open_msg: "cannot open the token file",
        read_msg: "cannot read the token file",
        large_msg: "the token file is too large",
        empty_msg: "the token file is empty",
    })
}

/// Every message names the SOURCE the caller actually used. Half of these were
/// once hardcoded to the file wording, so a `--token-env` failure sent the
/// reader looking for a file that was never involved.
struct TokenRead {
    trim: bool,
    max: usize,
    warn_mode: bool,
    open_msg: &'static str,
    read_msg: &'static str,
    large_msg: &'static str,
    empty_msg: &'static str,
}

fn read_token_bytes(path: &str, m: TokenRead) -> Result<Zeroizing<Vec<u8>>, &'static str> {
    let mut f = libthyla_rs::fs::File::open(path).map_err(|_| m.open_msg)?;
    // Warn, as npxf does, rather than refuse: the operator may have a reason,
    // and a mount that fails on a permission bit is worse than one that says so.
    // The token is a long-lived credential shared with the far end, and a
    // world-readable one is shared with everyone on this machine too.
    if m.warn_mode {
        if let Ok(md) = f.metadata() {
            let other = md.permissions() & 0o077;
            if other != 0 {
                say!(
                    "haul: warning: {} is readable beyond its owner (mode {:04o}) -- chmod 600 it",
                    path,
                    md.permissions() & 0o7777
                );
            }
        }
    }
    // Read into a fixed buffer rather than read_to_end + a length check: the
    // check has to come after the allocation, so `-t /dev/zero` would already
    // have consumed the heap by the time it fired. One byte over the cap is
    // enough to detect the overflow without ever holding more than the cap.
    let mut buf: Vec<u8> = alloc::vec![0u8; m.max + 1];
    let mut n = 0usize;
    while n < buf.len() {
        match f.read(&mut buf[n..]) {
            Ok(0) => break,
            Ok(got) => n += got,
            Err(_) => return Err(m.read_msg),
        }
    }
    if n > m.max {
        return Err(m.large_msg);
    }
    buf.truncate(n);
    // npxf::trim_token_file, not an inline pop: the exact bytes trimmed decide
    // the PSK, so the rule lives in one documented place with a test on each
    // side of the wire.
    if m.trim {
        npxf::trim_token_file(&mut buf);
    }
    if buf.is_empty() {
        return Err(m.empty_msg);
    }
    Ok(Zeroizing::new(buf))
}

fn parse_args(args: Args) -> Result<Parsed, &'static str> {
    // Collect argv as &str up front so the grammar itself can be a pure
    // function over strings -- haul::cmdline::plan, which is where the option/
    // operand boundary is decided AND tested. Only the two token SOURCES need
    // syscalls, and they are resolved after the grammar has spoken.
    let mut argv: Vec<&str> = Vec::new();
    let mut i = 1usize; // argv[0] is the program name
    while args.get(i).is_some() {
        match args.get_str(i) {
            Some(v) => argv.push(v),
            None => return Err("argument is not UTF-8"),
        }
        i += 1;
    }

    let plan = match cmdline::plan(&argv) {
        Ok(p) => p,
        Err(cmdline::Bad::WantsUsage) => {
            let _ = t_putstr(USAGE);
            return Err("");
        }
        Err(cmdline::Bad::MissingValue(m)) => return Err(m),
        Err(cmdline::Bad::UnknownOption) => return Err("unknown option"),
        Err(cmdline::Bad::DashAfterOperands) => {
            return Err("an option must come before the address; to run a command whose name \
                        starts with a dash, put -- after the mountpoint")
        }
    };

    if plan.verbose {
        VERBOSE.store(1, Ordering::Relaxed);
    }
    let token = match &plan.token {
        Some(cmdline::TokenSource::File(path)) => Some(read_token_file(path)?),
        Some(cmdline::TokenSource::Env(name)) => Some(read_token_env(name)?),
        None => None,
    };

    Ok(Parsed {
        addr: plan.addr,
        mountpoint: plan.mountpoint,
        aname: plan.aname,
        token,
        cmd: plan.cmd,
    })
}

/// Run npxf's three flights on the connected socket and return the live
/// channel.
///
/// FAILS CLOSED ON THE CSPRNG. The ephemeral scalar is the whole of the
/// session's forward secrecy; there is no weaker source to fall back to, so a
/// kernel that will not give us entropy ends the mount here rather than
/// producing a channel that merely looks encrypted.
fn npxf_handshake(fd: i64, ready: Ready, token: &[u8]) -> Result<npxf::Session, &'static str> {
    let mut eph = [0u8; 32];
    let got = libthyla_rs::rand::fill_bytes(&mut eph);
    if got.is_err() {
        return Err("no CSPRNG (needs CAP_CSPRNG_READ) -- refusing to handshake");
    }
    step!("entropy for the ephemeral: ok");

    // Wipe BEFORE the `?`. `Client::start` takes the scalar by value, so our copy
    // is dead either way -- but an early return would have skipped the wipe and
    // left 32 bytes of ephemeral on the stack. Unreachable today (the only
    // failure is EmptyToken, which both token sources already refuse upstream),
    // and unreachable is exactly the condition under which this rots.
    let started = npxf::Client::start(token, eph);
    eph.zeroize();
    let (client, msg1) = started.map_err(|_| "the token is empty")?;

    if !write_exact(fd, ready, &msg1) {
        return Err("handshake: the connection closed while sending our opening flight");
    }
    step!("sent flight 1 ({} bytes)", msg1.len());

    let mut msg2 = [0u8; npxf::MSG2_LEN];
    if !read_exact_before(fd, ready, &mut msg2, HANDSHAKE_MS) {
        return Err("handshake: no reply from the server (wrong token, not npxf, or unreachable)");
    }
    step!("got flight 2 ({} bytes)", msg2.len());

    let (mut session, msg3) = client.finish(&msg2).map_err(|e| match e {
        npxf::Error::ServerAuth => {
            "handshake: server authentication failed -- token mismatch, or intercepted"
        }
        npxf::Error::SmallOrderKey => "handshake: the server sent a small-order public key",
        _ => "handshake: refused",
    })?;

    if !write_exact(fd, ready, &msg3) {
        return Err("handshake: the connection closed while confirming");
    }
    step!("server authenticated, channel up");

    // Hold both directions to the same ceiling the plain path uses, so a server
    // cannot make us allocate npxf's full 8 MiB record just by claiming it.
    session.send.set_max_payload(MSG_MAX as usize);
    session.recv.set_max_payload(MSG_MAX as usize);
    Ok(session)
}

fn run(argv: Args) -> Result<(), &'static str> {
    let mut args = parse_args(argv)?;

    let (host, port) = haul::addr::split_dial(&args.addr)
        .ok_or("address needs a host and a port (host!port, or host:port)")?;
    let ip = Ipv4Addr::parse(host).map_err(|_| "the host is not a dotted-quad IPv4 address")?;
    let port = haul::addr::parse_port(port).ok_or("the port must be 1..=65535")?;
    let addr = SocketAddrV4::new(ip, port);
    step!("dialing {}", addr);
    let stream = TcpStream::connect(addr).map_err(|_| "connect")?;
    step!("connected");
    // The connection's READINESS fd, opened while the stream still exists to
    // name it. This is `/net/tcp/N/ready`, the QTPOLL sibling -- the only file
    // of the pair that carries readiness at all, and therefore the only one a
    // POLLOUT wait may be pointed at. Its own doc comment describes exactly this
    // use: "a bulk sender polls POLLOUT before retrying a write that returned 0".
    let ready_file = stream.ready_fd().map_err(|_| "cannot open the connection's ready file")?;
    let tcp_ready = Ready(ready_file.as_raw_fd() as i64);
    core::mem::forget(ready_file);

    // The pumps outlive this scope and address the connection by fd, so the
    // TcpStream must NOT drop (its Drop closes ctl + data, tearing the
    // connection down under them). Leaked deliberately: haul lives for the
    // mount's lifetime, so the connection's lifetime IS the process's. The
    // ready fd above is leaked for the same reason and in the same breath.
    let tcp_fd = stream.as_raw_fd() as i64;
    core::mem::forget(stream);

    // THE HANDSHAKE RUNS BEFORE THE PUMPS, and it must: it is a strictly
    // ordered three-flight exchange on the raw socket, so a pump concurrently
    // reading that socket would steal the server's reply. Once it returns, the
    // socket carries records only, and the pumps own it.
    // The handshake is the last thing that needs the token, so it leaves with
    // the handshake -- taken out of `args` and dropped (which wipes it) before
    // the mount goes up. Holding it would mean holding it for the LIFE of the
    // mount, and the park form's life is the machine's.
    let encrypted = args.token.is_some();
    let token = args.token.take();
    let handshake = match token.as_deref() {
        Some(t) => npxf_handshake(tcp_fd, tcp_ready, t).map(Some),
        // A plain-9P mount reaches the same code with nothing to wipe.
        None => Ok(None),
    };
    drop(token);
    let session = handshake?;
    let (sealer, opener) = match session {
        Some(s) => (Some(s.send), Some(s.recv)),
        None => (None, None),
    };

    // Two half-duplex pipes: c2s carries T-messages, s2c carries R-messages.
    let (c2s_rd, c2s_wr) = unsafe { t_pipe() };
    let (s2c_rd, s2c_wr) = unsafe { t_pipe() };
    if c2s_rd < 0 || c2s_wr < 0 || s2c_rd < 0 || s2c_wr < 0 {
        return Err("pipe pair");
    }

    // BOTH PUMPS BEFORE THE ATTACH. SYS_ATTACH_9P drives Tversion + Tattach
    // synchronously; with no pump running, the kernel would wait for an
    // Rversion nothing can deliver and the mount would hang rather than fail.
    spawn_pump(UpCtx {
        src: c2s_rd,
        dst: tcp_fd,
        dst_ready: tcp_ready,
        sealer,
    })?;
    spawn_pump(DownCtx {
        src: tcp_fd,
        dst: s2c_wr,
        // A pipe's own fd carries real POLLOUT, so it is its own readiness.
        dst_ready: Ready(s2c_wr),
        opener,
    })?;
    step!("pumps up; attaching (Tversion + Tattach run inside the syscall)");

    // The attach takes its own refs on both transport Spoors, so our copies of
    // the CLIENT ends close immediately after -- the session keeps the channel,
    // not these fds. (The SERVER ends stay open: they are the pumps'.)
    let root = unsafe {
        t_attach_9p(
            c2s_wr,
            s2c_rd,
            args.aname.as_ptr(),
            args.aname.len(),
            0,
        )
    };
    let _ = unsafe { t_close(c2s_wr) };
    let _ = unsafe { t_close(s2c_rd) };
    if root < 0 {
        // The pumps have the diagnosis: a server that hung up mid-handshake
        // stops one of them, and which one says whether we failed to send or
        // failed to hear back.
        return Err(match STOPPED.load(Ordering::Acquire) {
            STOP_UP => "attach (the connection closed while sending)",
            STOP_DOWN => "attach (the server closed without replying)",
            _ => "attach (9P handshake refused)",
        });
    }

    step!("attached; mounting at {}", args.mountpoint);
    let rc = unsafe {
        t_mount(
            args.mountpoint.as_ptr(),
            args.mountpoint.len(),
            root,
            T_MREPL,
        )
    };
    let _ = unsafe { t_close(root) };
    if rc < 0 {
        return Err("mount");
    }

    // Under -v, prove the mount from INSIDE this Proc before anyone else tries
    // to use it. A successful t_mount says the entry went into our table; it
    // does not say a walk crosses into the remote tree. Listing here separates
    // "the mount is wrong" from "the caller cannot see it", which are the two
    // failures that otherwise both present as `no such file or namespace entry`.
    //
    // GUARDED ON STOPPED, and that guard is load-bearing rather than tidy. This
    // is a blocking 9P round trip, and the kernel's Spoor transport sets
    // `set_recv_deadline = NULL` -- a backend with a NULL op ignores deadlines
    // and the recv just blocks. If the peer hangs up between t_mount and here,
    // both pumps reach `finish` and die, and A PUMP CLOSES NOTHING by design:
    // `s2c_wr` is still open, held by a dead thread's leaked ctx, so the kernel
    // never sees EOF on `s2c_rd` and this read_dir never returns. That is a
    // permanent silent hang in the one straight-line call that sits BEFORE the
    // park loop whose whole job is to bound exactly this.
    //
    // The guard closes the REACHABLE window -- a peer that dies any time before
    // the check begins. It does NOT close the race where the peer dies DURING
    // the round trip, and that residue cannot be closed here: bounding it needs
    // either a deadline the Spoor transport does not offer, or the dying pump to
    // close the kernel's write end, which is the fd-recycle race `finish`
    // deliberately refuses. So the residue is announced instead of hidden -- the
    // step below prints BEFORE the call, so a hang has a location rather than
    // being a silent stop after the mount line.
    if VERBOSE.load(Ordering::Relaxed) != 0 && STOPPED.load(Ordering::Relaxed) == STOP_NONE {
        step!("mount check: listing {} ...", args.mountpoint);
        match libthyla_rs::fs::read_dir(args.mountpoint.as_str()) {
            Ok(rd) => {
                let mut n = 0usize;
                let mut first = String::new();
                for e in rd.flatten() {
                    if n == 0 {
                        first = String::from(e.file_name());
                    }
                    n += 1;
                }
                step!("mount check: {} entr(y/ies) here, first {:?}", n, first);
            }
            Err(_) => step!("mount check: CANNOT read {} -- the mount did not take", args.mountpoint),
        }
    }

    // Name the channel, always. Which mode is live is exactly the thing a
    // reader must never have to infer from the absence of a flag.
    say!(
        "haul: {} mounted at {} (aname {}, {})",
        args.addr,
        args.mountpoint,
        args.aname,
        if encrypted {
            "npxf encrypted"
        } else {
            "PLAIN 9P"
        }
    );

    // WITH A COMMAND: run it here, where the mount exists.
    //
    // A mount lands in the CALLING Proc's Territory and nowhere else (I-1), so
    // `haul ... &` from a shell mounts into haul's OWN namespace and the shell
    // sees nothing. That much is measured and settled:
    //   cat: /home/cora/host/hello.txt: no such file or namespace entry
    // while haul sat happily mounted, its own read_dir of the mountpoint
    // returning the five entries the server exports.
    //
    // The Plan 9 answer to that is rfork-mount-exec, which is this form: the
    // child is downstream of the mount rather than beside it. AND THE CHILD DID
    // NOT SEE IT EITHER -- measured twice, on a mountpoint inside another mount
    // and on a plain ramfs one, which refuted the nested-mount explanation that
    // fit the first run perfectly. Reading the kernel says it should work:
    // rfork_internal clones the mount table unconditionally, spawn reaches it
    // via rfork_with_caps(RFPROC, ..), and exec.c never touches a Territory. So
    // the mechanism is UNEXPLAINED, not understood-and-accepted; it is tracked
    // as its own chunk (memory/bug_nested_mount_lost_at_spawn_clone.md) with the
    // interactive scenario as its reproducer.
    //
    // Until that lands, this form runs the command but does not promise it the
    // tree. Delivering a mount to an EXISTING shell needs /srv (post the
    // connection, let the shell mount it) -- a separate chunk and a design
    // question, recorded in docs/HAUL-DESIGN.md.
    if !args.cmd.is_empty() {
        let mut c = libthyla_rs::process::Command::new(args.cmd[0].clone());
        c.args(args.cmd[1..].iter().cloned());
        let mut child = c.spawn().map_err(|_| "could not run the command")?;
        // Poll the child AND the transport, rather than blocking in wait().
        //
        // A blocking wait watches only the child, and the child is not the only
        // thing that can end. If a pump stops mid-session, nobody drains the
        // pipes, so every filesystem call the child makes into this mount blocks
        // forever -- and a wait that is watching only the child then waits
        // forever too, with the process holding a mount that cannot serve. The
        // park form below already handles exactly this in under 200 ms; the
        // command form had no bound at all.
        let status = loop {
            match child.try_wait() {
                Ok(Some(st)) => break st,
                Err(_) => return Err("waiting for the command"),
                Ok(None) => {}
            }
            if STOPPED.load(Ordering::Acquire) != STOP_NONE {
                say!(
                    "haul: {} closed the connection while the command was running",
                    args.addr
                );
                return Err("the connection ended under the command");
            }
            let _ = libthyla_rs::time::sleep(libthyla_rs::time::Duration::from_millis(50));
        };
        // The transport dies with us, which is correct: the command has run, so
        // the tree it needed is no longer needed.
        return if status.success() {
            Ok(())
        } else {
            Err("the command exited non-zero")
        };
    }

    // WITHOUT ONE: the mount lives exactly as long as this Proc does -- the
    // pumps ARE the transport, so exiting would tear the session down under
    // whoever is walking the tree. Park until a pump reports the channel ended.
    loop {
        if STOPPED.load(Ordering::Acquire) != STOP_NONE {
            say!("haul: {} closed the connection -- the mount is dead", args.addr);
            // NOT Ok(()). A supervisor that restarts on a non-zero exit would
            // read success for a mount that is gone, and the command form's twin
            // above already returns Err for the same event.
            return Err("the peer closed the connection");
        }
        let _ = libthyla_rs::time::sleep(libthyla_rs::time::Duration::from_millis(200));
    }
}

#[no_mangle]
pub extern "C" fn rs_main() -> i64 {
    match run(env::args()) {
        Ok(()) => 0,
        // The empty reason is --help / usage: already printed, and a second
        // line naming it as a failure would be wrong.
        Err("") => 2,
        Err(why) => {
            say!("haul: {}", why);
            1
        }
    }
}
