// The npxf secure channel, guest side -- PURE protocol, no syscalls.
//
// npxf (the operator's own tool, `~/projects/npxf`) exports a directory over
// 9P2000.L on an authenticated, encrypted channel. This module is the client
// half of that channel: the key schedule, the three handshake flights, and the
// AEAD record layer. It knows nothing about sockets, pipes or mounts -- main.rs
// does the I/O around it. That split is deliberate and load-bearing: it is what
// lets the whole protocol be exercised on the host against known-answer vectors
// produced by npxf's OWN implementation (`kat/vectors.txt`, generated by
// `kat/npxf_kat.cpp`), instead of only by booting a guest and hoping.
//
//   psk = HMAC-SHA256("npxf token v1", token)
//   h0  = SHA256("npxf-handshake-v1")
//
//     c->s   "NPXF" | ver | rsv[3] | CE     (40)    h1 = SHA256(h0 | msg1)
//     s->c   SE | HMAC(k_cfm, "server")     (64)    h2 = SHA256(h1 | SE)
//     c->s   HMAC(k_cfm, "client")          (32)
//
//   prk   = HKDF-Extract(salt = psk, ikm = X25519(own eph, peer eph))
//   k_c2s = HKDF-Expand(prk, "npxf c2s v1" | h2, 32)   -- client's SEND key
//   k_s2c = HKDF-Expand(prk, "npxf s2c v1" | h2, 32)   -- client's RECV key
//   k_cfm = HKDF-Expand(prk, "npxf cfm v1" | h2, 32)
//
// Records: len[4] LE | ciphertext[len-16] | tag[16], AAD = those four length
// bytes, nonce = 00000000 | LE64(counter), an independent counter per
// direction. One 9P message per record.
//
// THE TOKEN IS NEVER SENT, in any form. Both ends prove possession by producing
// a MAC that only a holder could produce, so there is no bearer credential on
// the wire for a middlebox or a hostile server to capture and replay.
//
// WHY THE EPHEMERAL IS AN ARGUMENT, not generated in here: a hidden RNG
// dependency would make the handshake untestable and would hide WHERE the
// randomness comes from. The caller passes it in, so the KAT can pin the exact
// scalar npxf's vectors used, and main.rs is visibly the one place that must
// reach the kernel CSPRNG (and fail closed if it cannot).

use alloc::vec::Vec;

use chacha20poly1305::aead::AeadInPlace;
use chacha20poly1305::{ChaCha20Poly1305, KeyInit};
use hkdf::Hkdf;
use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};
use subtle::ConstantTimeEq;
use zeroize::Zeroize;

type HmacSha256 = Hmac<Sha256>;

pub const MSG1_LEN: usize = 40;
pub const MSG2_LEN: usize = 64;
pub const MSG3_LEN: usize = 32;
pub const RECORD_HDR: usize = 4;
pub const TAG_LEN: usize = 16;
pub const KEY_LEN: usize = 32;
pub const PROTOCOL_VERSION: u8 = 1;

const MAGIC: [u8; 4] = *b"NPXF";

/// npxf's own ceiling on one record's plaintext. The server clamps the
/// negotiated 9P msize to this, so a peer claiming more is out of protocol.
pub const MAX_RECORD_PAYLOAD: usize = 8 << 20;

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Error {
    /// The token was empty. npxf refuses this on both sides rather than
    /// deriving a key from nothing.
    EmptyToken,
    /// X25519 produced the all-zero point: the peer sent a small-order public
    /// key, so the shared secret would not depend on our contribution.
    SmallOrderKey,
    /// The server's confirmation MAC did not verify -- a token mismatch, or an
    /// active attacker. Indistinguishable by design, and fatal either way.
    ServerAuth,
    /// A record's declared length is impossible (below the tag, or above the
    /// agreed ceiling).
    RecordLength,
    /// A record's tag did not verify. The stream was tampered with, reordered,
    /// truncated or replayed. Always fatal to the session.
    RecordAuth,
    /// The direction's nonce counter is exhausted. Refused rather than wrapped:
    /// a repeated nonce under one key breaks ChaCha20-Poly1305 completely.
    CounterExhausted,
    /// An operation was attempted on a session already poisoned by a failure.
    SessionDead,
    /// The plaintext handed to seal exceeds the channel's ceiling.
    PayloadTooLarge,
}

/// HMAC-SHA256(key, msg) -- the one-shot npxf uses everywhere.
fn hmac(key: &[u8], msg: &[u8]) -> [u8; 32] {
    // new_from_slice's error is length-related and HMAC accepts any key length,
    // so this cannot fail; expect() documents that rather than hiding it.
    let mut m = <HmacSha256 as Mac>::new_from_slice(key).expect("HMAC accepts any key length");
    m.update(msg);
    m.finalize().into_bytes().into()
}

fn sha256_two(a: &[u8], b: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(a);
    h.update(b);
    h.finalize().into()
}

/// Turn an arbitrary-length token into the 32-byte pre-shared key.
pub fn derive_psk(token: &[u8]) -> Result<[u8; 32], Error> {
    if token.is_empty() {
        return Err(Error::EmptyToken);
    }
    Ok(hmac(b"npxf token v1", token))
}

fn transcript_start() -> [u8; 32] {
    Sha256::digest(b"npxf-handshake-v1").into()
}

/// HKDF-Expand(prk, label | transcript, 32).
fn expand_label(prk: &[u8; 32], label: &[u8], h2: &[u8; 32]) -> [u8; 32] {
    let hk = Hkdf::<Sha256>::from_prk(prk).expect("a 32-byte PRK is exactly SHA-256's length");
    let mut info = Vec::with_capacity(label.len() + h2.len());
    info.extend_from_slice(label);
    info.extend_from_slice(h2);
    let mut out = [0u8; 32];
    hk.expand(&info, &mut out)
        .expect("32 bytes is far below HKDF's 255*32 ceiling");
    out
}

/// The three keys a completed handshake yields.
struct Derived {
    c2s: [u8; 32],
    s2c: [u8; 32],
    cfm: [u8; 32],
}

impl Drop for Derived {
    fn drop(&mut self) {
        self.c2s.zeroize();
        self.s2c.zeroize();
        self.cfm.zeroize();
    }
}

/// X25519 with npxf's contributory-behaviour check.
fn dh(sk: &[u8; 32], peer: &[u8; 32]) -> Result<[u8; 32], Error> {
    let mut shared = x25519_dalek::x25519(*sk, *peer);
    // An all-zero result means the peer chose a small-order point, so the
    // shared secret does not depend on our ephemeral at all. npxf aborts here
    // and so must we -- accepting it would let a peer fix the session keys.
    if shared.ct_eq(&[0u8; 32]).into() {
        shared.zeroize();
        return Err(Error::SmallOrderKey);
    }
    Ok(shared)
}

fn derive(psk: &[u8; 32], sk: &[u8; 32], peer: &[u8; 32], h2: &[u8; 32]) -> Result<Derived, Error> {
    let mut shared = dh(sk, peer)?;
    let (mut prk, _) = Hkdf::<Sha256>::extract(Some(psk.as_slice()), &shared);
    shared.zeroize();

    // GenericArray is Copy, so `into()` COPIES the PRK rather than consuming
    // it. Both the original and the copy have to be wiped -- zeroizing only
    // `prk` would leave the whole key schedule's root sitting on the stack,
    // which is precisely the kind of leak that survives review because the one
    // visible `zeroize()` call looks like it covered the subject.
    let mut prk_bytes: [u8; 32] = prk.into();
    let out = Derived {
        c2s: expand_label(&prk_bytes, b"npxf c2s v1", h2),
        s2c: expand_label(&prk_bytes, b"npxf s2c v1", h2),
        cfm: expand_label(&prk_bytes, b"npxf cfm v1", h2),
    };
    prk_bytes.zeroize();
    prk.zeroize();
    Ok(out)
}

fn confirm_tag(cfm: &[u8; 32], who: &[u8]) -> [u8; 32] {
    hmac(cfm, who)
}

// ------------------------------------------------------------------ handshake

/// The client half of the handshake, between flight 1 and flight 2.
pub struct Client {
    psk: [u8; 32],
    eph_sk: [u8; 32],
    h1: [u8; 32],
}

impl Drop for Client {
    fn drop(&mut self) {
        self.psk.zeroize();
        self.eph_sk.zeroize();
    }
}

impl Client {
    /// Begin: derive the PSK, compute our ephemeral public key, and produce
    /// flight 1. `eph_sk` MUST come from a CSPRNG -- the forward secrecy of the
    /// whole session rests on it being unpredictable.
    pub fn start(token: &[u8], eph_sk: [u8; 32]) -> Result<(Self, [u8; MSG1_LEN]), Error> {
        let psk = derive_psk(token)?;
        let eph_pk = x25519_dalek::x25519(eph_sk, x25519_dalek::X25519_BASEPOINT_BYTES);

        let mut msg1 = [0u8; MSG1_LEN];
        msg1[..4].copy_from_slice(&MAGIC);
        msg1[4] = PROTOCOL_VERSION;
        // msg1[5..8] stay zero: the reserved bytes are covered by the
        // transcript, so a peer cannot smuggle anything through them.
        msg1[8..40].copy_from_slice(&eph_pk);

        let h1 = sha256_two(&transcript_start(), &msg1);
        Ok((Client { psk, eph_sk, h1 }, msg1))
    }

    /// Consume flight 2, authenticate the server, and produce flight 3 plus the
    /// session keys.
    ///
    /// Takes `self` by value: a handshake is single-use, and the type system
    /// says so rather than a comment.
    pub fn finish(self, msg2: &[u8; MSG2_LEN]) -> Result<(Session, [u8; MSG3_LEN]), Error> {
        let mut se_pk = [0u8; 32];
        se_pk.copy_from_slice(&msg2[..32]);

        let h2 = sha256_two(&self.h1, &se_pk);
        let d = derive(&self.psk, &self.eph_sk, &se_pk, &h2)?;

        // Constant-time, and BEFORE anything else is done with the keys: a
        // server that cannot produce this MAC does not hold the token.
        let want = confirm_tag(&d.cfm, b"server");
        if !bool::from(want.ct_eq(&msg2[32..64])) {
            return Err(Error::ServerAuth);
        }

        let msg3 = confirm_tag(&d.cfm, b"client");
        Ok((Session::new(d.c2s, d.s2c), msg3))
    }
}

/// A live channel: our send direction and our receive direction.
pub struct Session {
    pub send: Sealer,
    pub recv: Opener,
}

impl Session {
    fn new(send_key: [u8; 32], recv_key: [u8; 32]) -> Self {
        Session {
            send: Sealer::new(send_key),
            recv: Opener::new(recv_key),
        }
    }
}

// --------------------------------------------------------------- record layer

fn nonce_for(counter: u64) -> [u8; 12] {
    let mut n = [0u8; 12];
    n[4..].copy_from_slice(&counter.to_le_bytes());
    n
}

/// The outbound half of a channel.
pub struct Sealer {
    key: [u8; KEY_LEN],
    counter: u64,
    max_payload: usize,
    dead: bool,
}

impl Drop for Sealer {
    fn drop(&mut self) {
        self.key.zeroize();
    }
}

impl Sealer {
    fn new(key: [u8; KEY_LEN]) -> Self {
        Sealer {
            key,
            counter: 0,
            max_payload: MAX_RECORD_PAYLOAD,
            dead: false,
        }
    }

    /// Lower the ceiling on what this direction will emit.
    pub fn set_max_payload(&mut self, max: usize) {
        self.max_payload = max.min(MAX_RECORD_PAYLOAD);
    }

    /// Seal one plaintext into a complete record, appended to `out`.
    ///
    /// `out` is cleared first, so a caller reusing one buffer per message
    /// cannot accidentally emit the previous record's trailing bytes.
    pub fn seal(&mut self, pt: &[u8], out: &mut Vec<u8>) -> Result<(), Error> {
        if self.dead {
            return Err(Error::SessionDead);
        }
        if pt.len() > self.max_payload {
            return Err(Error::PayloadTooLarge);
        }

        out.clear();
        let clen = pt.len() + TAG_LEN;
        // The length is what the peer allocates against, so it must fit the
        // wire field exactly rather than by assumption.
        let clen32 = u32::try_from(clen).map_err(|_| Error::PayloadTooLarge)?;
        out.extend_from_slice(&clen32.to_le_bytes());
        out.extend_from_slice(pt);

        let cipher = ChaCha20Poly1305::new((&self.key).into());
        let nonce = nonce_for(self.counter);
        let aad = clen32.to_le_bytes();
        let tag = match cipher.encrypt_in_place_detached(&nonce.into(), &aad, &mut out[RECORD_HDR..])
        {
            Ok(t) => t,
            Err(_) => {
                // `out` currently holds the header followed by the PLAINTEXT --
                // encryption is in place and has not happened. A caller that
                // ignored this Err and wrote the buffer would put the message
                // on the wire in the clear, so clear it rather than trusting
                // the caller to notice.
                out.clear();
                self.dead = true;
                return Err(Error::RecordAuth);
            }
        };
        out.extend_from_slice(&tag);

        // Advance only after the record is fully formed, and refuse rather than
        // wrap: a reused nonce under one key is a total break, so exhaustion
        // must end the session, not silently repeat.
        self.counter = match self.counter.checked_add(1) {
            Some(n) => n,
            None => {
                self.dead = true;
                return Err(Error::CounterExhausted);
            }
        };
        Ok(())
    }
}

/// The inbound half of a channel.
pub struct Opener {
    key: [u8; KEY_LEN],
    counter: u64,
    max_payload: usize,
    dead: bool,
}

impl Drop for Opener {
    fn drop(&mut self) {
        self.key.zeroize();
    }
}

impl Opener {
    fn new(key: [u8; KEY_LEN]) -> Self {
        Opener {
            key,
            counter: 0,
            max_payload: MAX_RECORD_PAYLOAD,
            dead: false,
        }
    }

    pub fn set_max_payload(&mut self, max: usize) {
        self.max_payload = max.min(MAX_RECORD_PAYLOAD);
    }

    /// How many ciphertext bytes follow this header, validated against the
    /// ceiling BEFORE the caller allocates or reads them. Refusing here is what
    /// stops a hostile length claim from becoming a giant allocation.
    pub fn body_len(&self, hdr: &[u8; RECORD_HDR]) -> Result<usize, Error> {
        let clen = u32::from_le_bytes(*hdr) as usize;
        if clen < TAG_LEN {
            return Err(Error::RecordLength);
        }
        if clen - TAG_LEN > self.max_payload {
            return Err(Error::RecordLength);
        }
        Ok(clen)
    }

    /// Decrypt one record in place. `body` is exactly the `body_len` bytes that
    /// followed `hdr`: ciphertext then tag. On success the plaintext occupies
    /// the leading `body.len() - TAG_LEN` bytes.
    ///
    /// ANY failure poisons the session. A tag mismatch means the stream was
    /// tampered with or reordered, and continuing past one would let an
    /// attacker probe -- so the poison is structural, not a comment asking the
    /// caller to be careful.
    pub fn open<'a>(
        &mut self,
        hdr: &[u8; RECORD_HDR],
        body: &'a mut [u8],
    ) -> Result<&'a [u8], Error> {
        if self.dead {
            return Err(Error::SessionDead);
        }
        // A length violation is a protocol violation by the peer, so it is as
        // terminal as a tag failure. `body_len` on its own is a pure query and
        // does not poison -- but reaching it through `open` means we were
        // actually asked to decrypt that record, and the contract above says
        // ANY failure here ends the session.
        let want = match self.body_len(hdr) {
            Ok(n) => n,
            Err(e) => {
                self.dead = true;
                return Err(e);
            }
        };
        if body.len() != want {
            self.dead = true;
            return Err(Error::RecordLength);
        }

        let plen = body.len() - TAG_LEN;
        let (ct, tag) = body.split_at_mut(plen);

        let cipher = ChaCha20Poly1305::new((&self.key).into());
        let nonce = nonce_for(self.counter);
        if cipher
            .decrypt_in_place_detached(&nonce.into(), hdr, ct, (&*tag).into())
            .is_err()
        {
            self.dead = true;
            return Err(Error::RecordAuth);
        }

        self.counter = match self.counter.checked_add(1) {
            Some(n) => n,
            None => {
                self.dead = true;
                return Err(Error::CounterExhausted);
            }
        };
        Ok(&body[..plen])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---- the known-answer vectors, produced by npxf's OWN channel.cpp -------
    //
    // These are the whole point of this module being pure. Every value below
    // came out of `kat/npxf_kat.cpp`, which #includes npxf's channel.cpp so it
    // calls the reference `derive()`/`absorb()`/`confirm_tag()` rather than a
    // re-derivation of them. If this file and npxf ever disagree about a single
    // byte of the schedule, one of these fails and names the step.

    const VECTORS: &str = include_str!("../kat/vectors.txt");

    fn unhex(s: &str) -> Vec<u8> {
        assert!(s.len() % 2 == 0, "odd-length hex: {s}");
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("hex"))
            .collect()
    }

    /// Look one vector up by name. Panics if absent -- a silently-missing
    /// vector would turn an assertion into a no-op, which is the failure mode
    /// this whole fixture exists to prevent.
    fn vec_of(name: &str) -> Vec<u8> {
        for line in VECTORS.lines() {
            let line = line.trim();
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            let (k, v) = line.split_once('=').expect("vector line has no '='");
            if k.trim() == name {
                return unhex(v.trim());
            }
        }
        panic!("no vector named {name} in kat/vectors.txt");
    }

    fn arr32(name: &str) -> [u8; 32] {
        let v = vec_of(name);
        assert_eq!(v.len(), 32, "{name} should be 32 bytes");
        let mut a = [0u8; 32];
        a.copy_from_slice(&v);
        a
    }

    #[test]
    fn psk_matches_the_reference() {
        let token = vec_of("token");
        assert_eq!(derive_psk(&token).unwrap().to_vec(), vec_of("psk"));
    }

    #[test]
    fn an_empty_token_is_refused() {
        assert_eq!(derive_psk(b""), Err(Error::EmptyToken));
    }

    // Clamping is the classic silent interop break: npxf's ladder clamps the
    // scalar, and if x25519-dalek did not, every key would differ while the
    // code still "worked".
    #[test]
    fn base_mult_matches_the_reference() {
        let ce_pk = x25519_dalek::x25519(arr32("ce_sk"), x25519_dalek::X25519_BASEPOINT_BYTES);
        assert_eq!(ce_pk.to_vec(), vec_of("ce_pk"));
        let se_pk = x25519_dalek::x25519(arr32("se_sk"), x25519_dalek::X25519_BASEPOINT_BYTES);
        assert_eq!(se_pk.to_vec(), vec_of("se_pk"));
    }

    #[test]
    fn dh_matches_the_reference_from_both_sides() {
        assert_eq!(dh(&arr32("ce_sk"), &arr32("se_pk")).unwrap().to_vec(), vec_of("dh"));
        assert_eq!(dh(&arr32("se_sk"), &arr32("ce_pk")).unwrap().to_vec(), vec_of("dh"));
    }

    #[test]
    fn flight_one_is_byte_identical() {
        let (_c, msg1) = Client::start(&vec_of("token"), arr32("ce_sk")).unwrap();
        assert_eq!(msg1.to_vec(), vec_of("msg1"));
    }

    #[test]
    fn the_transcript_matches_the_reference() {
        assert_eq!(transcript_start().to_vec(), vec_of("h0"));
        let h1 = sha256_two(&transcript_start(), &vec_of("msg1"));
        assert_eq!(h1.to_vec(), vec_of("h1"));
        assert_eq!(sha256_two(&h1, &vec_of("se_pk")).to_vec(), vec_of("h2"));
    }

    #[test]
    fn the_three_session_keys_match_the_reference() {
        let d = derive(&arr32("psk"), &arr32("ce_sk"), &arr32("se_pk"), &arr32("h2")).unwrap();
        assert_eq!(d.c2s.to_vec(), vec_of("k_c2s"));
        assert_eq!(d.s2c.to_vec(), vec_of("k_s2c"));
        assert_eq!(d.cfm.to_vec(), vec_of("k_cfm"));
    }

    #[test]
    fn the_confirmation_tags_match_the_reference() {
        let cfm = arr32("k_cfm");
        assert_eq!(confirm_tag(&cfm, b"server").to_vec(), vec_of("tag_server"));
        assert_eq!(confirm_tag(&cfm, b"client").to_vec(), vec_of("tag_client"));
    }

    /// The whole client flight, end to end, against the reference bytes.
    #[test]
    fn a_full_handshake_reproduces_the_reference() {
        let (c, msg1) = Client::start(&vec_of("token"), arr32("ce_sk")).unwrap();
        assert_eq!(msg1.to_vec(), vec_of("msg1"));

        let mut msg2 = [0u8; MSG2_LEN];
        msg2.copy_from_slice(&vec_of("msg2"));
        let (session, msg3) = c.finish(&msg2).unwrap();

        assert_eq!(msg3.to_vec(), vec_of("msg3"));
        // The client SENDS on c2s and RECEIVES on s2c. Getting these backwards
        // is the kind of mistake that only shows up as an opaque tag failure.
        assert_eq!(session.send.key.to_vec(), vec_of("k_c2s"));
        assert_eq!(session.recv.key.to_vec(), vec_of("k_s2c"));
    }

    /// A wrong token must fail at the SERVER-AUTH step, not somewhere vague.
    #[test]
    fn a_wrong_token_fails_server_authentication() {
        let (c, _) = Client::start(b"the wrong token entirely", arr32("ce_sk")).unwrap();
        let mut msg2 = [0u8; MSG2_LEN];
        msg2.copy_from_slice(&vec_of("msg2"));
        // `.err()` rather than comparing the Result: Session deliberately
        // implements neither Debug nor PartialEq, because a derived Debug on a
        // key holder is a leak waiting for its first stray log line.
        assert_eq!(c.finish(&msg2).err(), Some(Error::ServerAuth));
    }

    /// A flipped bit anywhere in the server's MAC must be caught.
    #[test]
    fn a_tampered_server_tag_fails() {
        for bit in [0usize, 7, 128, 255] {
            let (c, _) = Client::start(&vec_of("token"), arr32("ce_sk")).unwrap();
            let mut msg2 = [0u8; MSG2_LEN];
            msg2.copy_from_slice(&vec_of("msg2"));
            msg2[32 + bit / 8] ^= 1 << (bit % 8);
            assert_eq!(c.finish(&msg2).err(), Some(Error::ServerAuth), "bit {bit}");
        }
    }

    /// A swapped server ephemeral must break the handshake -- that is the
    /// transcript binding doing its job.
    #[test]
    fn a_swapped_server_ephemeral_fails() {
        let (c, _) = Client::start(&vec_of("token"), arr32("ce_sk")).unwrap();
        let mut msg2 = [0u8; MSG2_LEN];
        msg2.copy_from_slice(&vec_of("msg2"));
        msg2[0] ^= 0x01;
        assert_eq!(c.finish(&msg2).err(), Some(Error::ServerAuth));
    }

    /// Contributory behaviour: a small-order peer key aborts rather than
    /// yielding a session whose keys the peer alone chose.
    #[test]
    fn a_small_order_peer_key_aborts() {
        // The canonical low-order points from RFC 7748 / the curve25519 test
        // set: all of them drive the ladder to the identity.
        let zero = [0u8; 32];
        assert_eq!(dh(&arr32("ce_sk"), &zero), Err(Error::SmallOrderKey));
        let mut one = [0u8; 32];
        one[0] = 1;
        assert_eq!(dh(&arr32("ce_sk"), &one), Err(Error::SmallOrderKey));
    }

    // ---- record layer -------------------------------------------------------

    fn session_from_vectors() -> Session {
        Session::new(arr32("k_c2s"), arr32("k_s2c"))
    }

    /// Both records, at counters 0 and 1, byte for byte. Emitting the second is
    /// what pins the counter: an implementation stuck on nonce 0 reproduces
    /// record 0 exactly and fails here.
    #[test]
    fn sealed_records_are_byte_identical_to_the_reference() {
        let mut s = session_from_vectors();
        let pt = vec_of("record_pt");
        let mut out = Vec::new();

        s.send.seal(&pt, &mut out).unwrap();
        assert_eq!(out, vec_of("record_c2s0"));

        s.send.seal(&pt, &mut out).unwrap();
        assert_eq!(out, vec_of("record_c2s1"), "the nonce counter must advance");
    }

    /// A round trip through an Opener keyed the same way -- the server's view
    /// of what we just sent.
    #[test]
    fn a_sealed_record_opens_back_to_the_plaintext() {
        let mut sealer = Sealer::new(arr32("k_c2s"));
        let mut opener = Opener::new(arr32("k_c2s"));
        let pt = vec_of("record_pt");

        for _ in 0..4 {
            let mut rec = Vec::new();
            sealer.seal(&pt, &mut rec).unwrap();
            let mut hdr = [0u8; RECORD_HDR];
            hdr.copy_from_slice(&rec[..RECORD_HDR]);
            let n = opener.body_len(&hdr).unwrap();
            assert_eq!(n, rec.len() - RECORD_HDR);
            let got = opener.open(&hdr, &mut rec[RECORD_HDR..]).unwrap();
            assert_eq!(got, &pt[..]);
        }
    }

    /// The reference records decrypt with the reference key -- the direction we
    /// actually consume as a client is the s2c one, but the KAT gives us c2s,
    /// so open them with a c2s-keyed Opener.
    #[test]
    fn the_reference_records_decrypt() {
        let mut opener = Opener::new(arr32("k_c2s"));
        for name in ["record_c2s0", "record_c2s1"] {
            let mut rec = vec_of(name);
            let mut hdr = [0u8; RECORD_HDR];
            hdr.copy_from_slice(&rec[..RECORD_HDR]);
            let got = opener.open(&hdr, &mut rec[RECORD_HDR..]).unwrap();
            assert_eq!(got, &vec_of("record_pt")[..], "{name}");
        }
    }

    /// A record replayed at the wrong counter must fail. This is the property
    /// that makes reordering and duplication detectable.
    #[test]
    fn a_replayed_record_fails() {
        let mut opener = Opener::new(arr32("k_c2s"));
        let mut rec = vec_of("record_c2s0");
        let mut hdr = [0u8; RECORD_HDR];
        hdr.copy_from_slice(&rec[..RECORD_HDR]);
        opener.open(&hdr, &mut rec[RECORD_HDR..]).unwrap();

        // The same record again. The opener now expects counter 1, so the tag
        // cannot verify -- a replay is caught by the nonce, not by any stored
        // history of what was seen.
        let mut again = vec_of("record_c2s0");
        assert_eq!(
            opener.open(&hdr, &mut again[RECORD_HDR..]),
            Err(Error::RecordAuth)
        );

        // ... and THAT failure poisons, so a genuine follow-on record is
        // refused rather than letting an attacker keep probing.
        let mut third = vec_of("record_c2s1");
        assert_eq!(
            opener.open(&hdr, &mut third[RECORD_HDR..]),
            Err(Error::SessionDead)
        );
    }

    /// Records delivered out of order must fail.
    #[test]
    fn an_out_of_order_record_fails() {
        let mut opener = Opener::new(arr32("k_c2s"));
        let mut rec = vec_of("record_c2s1"); // counter 1 arriving first
        let mut hdr = [0u8; RECORD_HDR];
        hdr.copy_from_slice(&rec[..RECORD_HDR]);
        assert_eq!(opener.open(&hdr, &mut rec[RECORD_HDR..]), Err(Error::RecordAuth));
    }

    /// Any tampering in the ciphertext is caught, and kills the session.
    #[test]
    fn a_tampered_record_fails_and_poisons() {
        let mut opener = Opener::new(arr32("k_c2s"));
        let mut rec = vec_of("record_c2s0");
        rec[RECORD_HDR + 2] ^= 0x40;
        let mut hdr = [0u8; RECORD_HDR];
        hdr.copy_from_slice(&rec[..RECORD_HDR]);
        assert_eq!(opener.open(&hdr, &mut rec[RECORD_HDR..]), Err(Error::RecordAuth));

        // ... and a subsequent GOOD record is refused, because the session is
        // over. Probing past an authentication failure is exactly what an
        // attacker wants.
        let mut good = vec_of("record_c2s0");
        assert_eq!(
            opener.open(&hdr, &mut good[RECORD_HDR..]),
            Err(Error::SessionDead)
        );
    }

    /// The length field is AAD, so tampering with it is caught even though it
    /// is not encrypted.
    #[test]
    fn a_tampered_length_fails() {
        let mut opener = Opener::new(arr32("k_c2s"));
        let rec = vec_of("record_c2s0");
        let mut hdr = [0u8; RECORD_HDR];
        hdr.copy_from_slice(&rec[..RECORD_HDR]);
        hdr[0] = hdr[0].wrapping_sub(1); // claim one byte less

        let mut body = rec[RECORD_HDR..].to_vec();
        body.pop(); // ... and actually deliver one byte less
        assert_eq!(opener.open(&hdr, &mut body), Err(Error::RecordAuth));
    }

    #[test]
    fn an_impossible_length_is_refused_before_allocation() {
        let opener = Opener::new(arr32("k_c2s"));
        // Below the tag: cannot be a record at all.
        for n in [0u32, 1, 15] {
            assert_eq!(opener.body_len(&n.to_le_bytes()), Err(Error::RecordLength));
        }
        // Exactly the tag is an empty but well-formed record.
        assert_eq!(opener.body_len(&16u32.to_le_bytes()), Ok(16));
        // Above the ceiling.
        let too_big = (MAX_RECORD_PAYLOAD + TAG_LEN + 1) as u32;
        assert_eq!(opener.body_len(&too_big.to_le_bytes()), Err(Error::RecordLength));
        // ... and exactly the ceiling still passes, so the bound is not off by
        // one in the safe-looking direction.
        let exact = (MAX_RECORD_PAYLOAD + TAG_LEN) as u32;
        assert_eq!(opener.body_len(&exact.to_le_bytes()), Ok(exact as usize));
    }

    #[test]
    fn a_lowered_ceiling_is_honoured_in_both_directions() {
        let mut s = session_from_vectors();
        s.send.set_max_payload(64);
        s.recv.set_max_payload(64);

        let mut out = Vec::new();
        assert_eq!(s.send.seal(&[0u8; 65], &mut out), Err(Error::PayloadTooLarge));
        assert!(s.send.seal(&[0u8; 64], &mut out).is_ok());

        let over = (64 + TAG_LEN + 1) as u32;
        assert_eq!(s.recv.body_len(&over.to_le_bytes()), Err(Error::RecordLength));
    }

    /// A body whose length disagrees with the header is refused rather than
    /// decrypted against whatever was there.
    #[test]
    fn a_short_body_is_refused() {
        let mut opener = Opener::new(arr32("k_c2s"));
        let rec = vec_of("record_c2s0");
        let mut hdr = [0u8; RECORD_HDR];
        hdr.copy_from_slice(&rec[..RECORD_HDR]);
        let mut body = rec[RECORD_HDR..rec.len() - 1].to_vec();
        assert_eq!(opener.open(&hdr, &mut body), Err(Error::RecordLength));
    }

    /// An exhausted counter refuses rather than wrapping to a reused nonce.
    #[test]
    fn an_exhausted_counter_refuses() {
        let mut s = Sealer::new(arr32("k_c2s"));
        s.counter = u64::MAX;
        let mut out = Vec::new();
        assert_eq!(s.seal(b"x", &mut out), Err(Error::CounterExhausted));
        // ... and stays refused.
        assert_eq!(s.seal(b"x", &mut out), Err(Error::SessionDead));
    }

    /// An empty plaintext is a legal record (16 bytes of tag, no ciphertext).
    #[test]
    fn an_empty_record_round_trips() {
        let mut sealer = Sealer::new(arr32("k_c2s"));
        let mut opener = Opener::new(arr32("k_c2s"));
        let mut rec = Vec::new();
        sealer.seal(&[], &mut rec).unwrap();
        assert_eq!(rec.len(), RECORD_HDR + TAG_LEN);
        let mut hdr = [0u8; RECORD_HDR];
        hdr.copy_from_slice(&rec[..RECORD_HDR]);
        assert_eq!(opener.open(&hdr, &mut rec[RECORD_HDR..]).unwrap(), b"");
    }

    /// A length violation reached through `open` is as terminal as a bad tag.
    /// `body_len` alone is a pure query and must NOT poison -- the caller uses
    /// it to size a buffer before committing to anything.
    #[test]
    fn a_length_violation_through_open_poisons_but_a_query_does_not() {
        let mut opener = Opener::new(arr32("k_c2s"));
        opener.set_max_payload(32);

        // The query form: refuses, leaves the session usable.
        let over = (64 + TAG_LEN) as u32;
        assert_eq!(opener.body_len(&over.to_le_bytes()), Err(Error::RecordLength));

        // The same violation through open(): terminal.
        let mut body = vec![0u8; 64 + TAG_LEN];
        assert_eq!(
            opener.open(&over.to_le_bytes(), &mut body),
            Err(Error::RecordLength)
        );

        // ... and now even a well-formed record is refused.
        opener.set_max_payload(MAX_RECORD_PAYLOAD);
        let mut good = vec_of("record_c2s0");
        let mut hdr = [0u8; RECORD_HDR];
        hdr.copy_from_slice(&good[..RECORD_HDR]);
        assert_eq!(
            opener.open(&hdr, &mut good[RECORD_HDR..]),
            Err(Error::SessionDead)
        );
    }

    /// seal() clears its output buffer, so a caller reusing one Vec cannot
    /// emit the previous record's tail.
    #[test]
    fn seal_does_not_append_to_a_dirty_buffer() {
        let mut s = Sealer::new(arr32("k_c2s"));
        let mut out = vec![0xAA; 999];
        s.seal(&vec_of("record_pt"), &mut out).unwrap();
        assert_eq!(out, vec_of("record_c2s0"));
    }

    // ---- live interop against the REAL npxf server --------------------------
    //
    // The vectors above prove this code reproduces npxf's arithmetic. They
    // cannot prove it INTEROPERATES, because a fixture is a recording: both
    // sides of a mistake I made when generating it would agree. This drives the
    // actual `npxf-server` binary over TCP and makes it accept our handshake
    // and answer a real 9P message.
    //
    // #[ignore] because it needs a server: an absent one must SKIP loudly on
    // request, never silently pass in the default suite.
    //
    //   npxf-server -l 127.0.0.1:5640 -r <tree> -t <tokenfile> -R
    //   HAUL_NPXF_ADDR=127.0.0.1:5640 HAUL_NPXF_TOKEN=<token> \
    //     cargo test -p haul --lib --no-default-features \
    //       --target aarch64-apple-darwin -- --ignored --nocapture

    #[test]
    #[ignore]
    fn interoperates_with_a_live_npxf_server() {
        use std::io::{Read, Write};

        let addr = std::env::var("HAUL_NPXF_ADDR")
            .expect("set HAUL_NPXF_ADDR=host:port to run the live interop test");
        let token = std::env::var("HAUL_NPXF_TOKEN")
            .expect("set HAUL_NPXF_TOKEN to the server's token");

        let mut sock = std::net::TcpStream::connect(&addr).expect("connect to npxf-server");
        sock.set_read_timeout(Some(std::time::Duration::from_secs(15)))
            .unwrap();

        // A REAL random ephemeral, not the KAT's: this must work for any
        // scalar, and a fixed one would quietly test only the recorded case.
        let mut eph = [0u8; 32];
        getrandom_for_test(&mut eph);

        let (client, msg1) = Client::start(token.as_bytes(), eph).unwrap();
        sock.write_all(&msg1).expect("send flight 1");

        let mut msg2 = [0u8; MSG2_LEN];
        sock.read_exact(&mut msg2)
            .expect("server closed instead of replying -- wrong token?");

        let (mut session, msg3) = client
            .finish(&msg2)
            .expect("the real server's confirmation MAC must verify");
        sock.write_all(&msg3).expect("send flight 3");

        // The handshake is only half the claim. Speak actual 9P: a Tversion,
        // and an Rversion back, decrypted. THAT is interoperation.
        let tversion = vec_of("record_pt");
        let mut rec = Vec::new();
        session.send.seal(&tversion, &mut rec).unwrap();
        sock.write_all(&rec).expect("send Tversion record");

        let mut hdr = [0u8; RECORD_HDR];
        sock.read_exact(&mut hdr).expect("read the reply header");
        let n = session.recv.body_len(&hdr).expect("reply length is sane");
        let mut body = vec![0u8; n];
        sock.read_exact(&mut body).expect("read the reply body");

        let pt = session
            .recv
            .open(&hdr, &mut body)
            .expect("the server's reply must authenticate");

        // Rversion is type 101, and its size field must match the payload --
        // the same agreement npxf's server enforces on our messages.
        assert!(pt.len() >= 7, "runt reply: {} bytes", pt.len());
        assert_eq!(
            u32::from_le_bytes([pt[0], pt[1], pt[2], pt[3]]) as usize,
            pt.len(),
            "the reply's 9P size field must equal the record payload length"
        );
        assert_eq!(pt[4], 101, "expected Rversion (101), got type {}", pt[4]);
        let vlen = u16::from_le_bytes([pt[11], pt[12]]) as usize;
        assert_eq!(
            &pt[13..13 + vlen],
            b"9P2000.L",
            "the server must agree on 9P2000.L"
        );
        std::println!(
            "interop OK: handshake + Tversion/Rversion against {addr}, msize {}",
            u32::from_le_bytes([pt[7], pt[8], pt[9], pt[10]])
        );
    }

    #[cfg(test)]
    fn getrandom_for_test(buf: &mut [u8]) {
        use std::io::Read;
        // The host's own entropy. This is test scaffolding only -- the guest
        // gets its ephemeral from SYS_GETRANDOM, never from a file.
        std::fs::File::open("/dev/urandom")
            .expect("/dev/urandom")
            .read_exact(buf)
            .expect("read entropy");
    }
}
