// corvus-mint -- A-5c-b host-target system-identity minter.
//
// Generates the admin hybrid keypair, wraps it under the build-time system
// passphrase (-> system-wrap) and under a 24-word BIP-39 recovery phrase
// (-> system-recovery-wrap), self-verifies BOTH keyslots unwrap to the same
// keypair, writes the two CRVS-v1 blobs into <out-dir>, and prints the recovery
// phrase to stdout (the build logs it -- forensic, like the mkfs seed). Reuses
// corvus's exact crypto via corvus-crypto so the wraps are byte-identical to
// what the on-device corvus reads at boot.
//
// v1.0: the build-time system passphrase defaults to the known "thylacine"
// constant (overridable via CORVUS_SYSTEM_PASSPHRASE) so joey's ADMIN_ELEVATE
// boot E2E stays green and the build is reproducible; a v1.x installer supplies
// a real per-install secret. The WRAP is real Argon2id+AEGIS either way.
//
// A-5c-c: the recovery-phrase ENTROPY is DETERMINISTIC (derived from
// CORVUS_SYSTEM_RECOVERY_SEED, default DEFAULT_RECOVERY_SEED_HEX) -- the same
// "build-baked known secret" posture as the system passphrase + the mkfs seed.
// This lets joey's boot E2E drive a LIVE RECOVER(system) with a phrase it knows
// (surfaced via the generated header `emit-phrase` writes). The admin keypair +
// the two wraps' salts/nonces stay random per build; ONLY the recovery-phrase
// entropy is pinned (joey needs the phrase, not the keypair). A v1.x installer
// supplies real per-install randomness here too.
//
// Two modes:
//   corvus-mint <out-dir>            bake system-wrap + system-recovery-wrap
//   corvus-mint emit-phrase <path>   write the system recovery phrase as a C
//                                    header (no pool/keypair) so joey's build
//                                    can #include it BEFORE the pool bake runs.

use corvus_crypto::{
    bip39_encode, generate_hybrid_keypair, make_recovery_wrap, unwrap_keypair_passphrase,
    unwrap_recovery, wipe, wrap_keypair_passphrase, RECOVERY_ENTROPY_BYTES, SYSTEM_WRAP_SUBJECT,
};
use std::io::Write;

// Default deterministic system recovery seed (32 bytes / 64 hex). Overridable
// via CORVUS_SYSTEM_RECOVERY_SEED. Clearly a test value (A-5c-b themed); the
// security posture is identical to the build-baked "thylacine" system
// passphrase -- documented in docs/reference/105-corvus-recovery.md.
const DEFAULT_RECOVERY_SEED_HEX: &str =
    "a5cba5cba5cba5cba5cba5cba5cba5cba5cba5cba5cba5cba5cba5cba5cba5cb";

fn hexval(c: u8) -> Option<u8> {
    match c {
        b'0'..=b'9' => Some(c - b'0'),
        b'a'..=b'f' => Some(c - b'a' + 10),
        b'A'..=b'F' => Some(c - b'A' + 10),
        _ => None,
    }
}

fn parse_seed_hex(s: &str) -> Option<[u8; RECOVERY_ENTROPY_BYTES]> {
    let s = s.trim();
    if s.len() != RECOVERY_ENTROPY_BYTES * 2 {
        return None;
    }
    let b = s.as_bytes();
    let mut out = [0u8; RECOVERY_ENTROPY_BYTES];
    for i in 0..RECOVERY_ENTROPY_BYTES {
        out[i] = (hexval(b[2 * i])? << 4) | hexval(b[2 * i + 1])?;
    }
    Some(out)
}

// The deterministic recovery entropy: CORVUS_SYSTEM_RECOVERY_SEED or the default.
// Both modes derive the SAME phrase + wrap from it, so the header phrase opens
// the baked system-recovery-wrap by construction (no drift possible).
fn recovery_seed_entropy() -> [u8; RECOVERY_ENTROPY_BYTES] {
    let hex = std::env::var("CORVUS_SYSTEM_RECOVERY_SEED")
        .unwrap_or_else(|_| DEFAULT_RECOVERY_SEED_HEX.to_string());
    parse_seed_hex(&hex).unwrap_or_else(|| {
        eprintln!("corvus-mint: CORVUS_SYSTEM_RECOVERY_SEED must be exactly 64 hex chars");
        std::process::exit(2);
    })
}

fn write_blob(path: &str, bytes: &[u8]) {
    let mut f = std::fs::File::create(path).unwrap_or_else(|e| {
        eprintln!("corvus-mint: create {}: {}", path, e);
        std::process::exit(1);
    });
    f.write_all(bytes).unwrap_or_else(|e| {
        eprintln!("corvus-mint: write {}: {}", path, e);
        std::process::exit(1);
    });
    f.sync_all().ok();
}

// emit-phrase: write the system recovery phrase (derived from the seed) as a C
// header for joey's build to #include. No keypair, no pool -- pure derivation,
// so it can run BEFORE the userspace build (the pool bake runs later, after
// joey is already compiled). Both this and the bake derive the phrase from the
// same seed, so they agree by construction.
fn emit_phrase_header(path: &str) {
    let entropy = recovery_seed_entropy();
    let phrase = bip39_encode(&entropy);
    let phrase_str = std::str::from_utf8(&phrase).expect("corvus-mint: phrase not utf8");
    let body = format!(
        "// GENERATED by tools/corvus-mint emit-phrase (A-5c-c). Do not edit.\n\
         // The host-baked system recovery phrase for the build seed, surfaced so\n\
         // joey's boot E2E can drive a LIVE RECOVER(system). Build-baked known\n\
         // test secret (same posture as the 'thylacine' system passphrase).\n\
         #pragma once\n\
         #define CORVUS_SYSTEM_RECOVERY_PHRASE \"{}\"\n",
        phrase_str
    );
    let mut f = std::fs::File::create(path).unwrap_or_else(|e| {
        eprintln!("corvus-mint: create header {}: {}", path, e);
        std::process::exit(1);
    });
    f.write_all(body.as_bytes()).unwrap_or_else(|e| {
        eprintln!("corvus-mint: write header {}: {}", path, e);
        std::process::exit(1);
    });
    f.sync_all().ok();
    eprintln!("corvus-mint: emitted system recovery phrase header -> {}", path);
}

fn bake(out_dir: &str) {
    let passphrase =
        std::env::var("CORVUS_SYSTEM_PASSPHRASE").unwrap_or_else(|_| "thylacine".to_string());

    let mut rng = rand::rngs::OsRng;

    let mut keypair = generate_hybrid_keypair(&mut rng).expect("corvus-mint: keygen failed");

    // system-wrap: the admin keypair under the system passphrase.
    let sw = wrap_keypair_passphrase(&mut rng, SYSTEM_WRAP_SUBJECT, passphrase.as_bytes(), &keypair)
        .expect("corvus-mint: system-wrap failed");

    // system-recovery-wrap: the SAME keypair under the DETERMINISTIC recovery
    // phrase (seed-derived; joey's header carries the matching phrase). The
    // wrap's salt/nonce are still random per build -- only the entropy is pinned.
    let mut entropy = recovery_seed_entropy();
    let phrase = bip39_encode(&entropy);
    let srw = make_recovery_wrap(&mut rng, SYSTEM_WRAP_SUBJECT, &entropy, &keypair)
        .expect("corvus-mint: system-recovery-wrap failed");

    // Self-verify BOTH keyslots unwrap to the EXACT keypair the device will read
    // -- catches any wrap/unwrap mismatch before the bytes are baked into the pool.
    let mut v1 = unwrap_keypair_passphrase(SYSTEM_WRAP_SUBJECT, passphrase.as_bytes(), &sw)
        .expect("corvus-mint: system-wrap self-verify unwrap failed");
    assert!(v1 == keypair, "corvus-mint: system-wrap self-verify MISMATCH");
    let mut v2 = unwrap_recovery(SYSTEM_WRAP_SUBJECT, &entropy, &srw)
        .expect("corvus-mint: system-recovery-wrap self-verify unwrap failed");
    assert!(v2 == keypair, "corvus-mint: system-recovery-wrap self-verify MISMATCH");

    write_blob(&format!("{}/system-wrap", out_dir), &sw.to_bytes());
    write_blob(&format!("{}/system-recovery-wrap", out_dir), &srw.to_bytes());

    // The recovery phrase -- to stdout for the build log. Deterministic (seed-
    // derived); the build can regenerate it via `emit-phrase` with the same seed.
    println!("{}", std::str::from_utf8(&phrase).expect("corvus-mint: phrase not utf8"));
    eprintln!(
        "corvus-mint: wrote system-wrap + system-recovery-wrap to {} (subject 'system', passphrase '{}')",
        out_dir, passphrase
    );

    wipe(&mut keypair);
    wipe(&mut entropy);
    wipe(&mut v1);
    wipe(&mut v2);
}

fn main() {
    let arg1 = std::env::args().nth(1).unwrap_or_else(|| {
        eprintln!("usage: corvus-mint <out-dir> | corvus-mint emit-phrase <header-path>");
        std::process::exit(2);
    });
    if arg1 == "emit-phrase" {
        let path = std::env::args().nth(2).unwrap_or_else(|| {
            eprintln!("usage: corvus-mint emit-phrase <header-path>");
            std::process::exit(2);
        });
        emit_phrase_header(&path);
        return;
    }
    bake(&arg1);
}
