#!/usr/bin/env python3
"""Write the Instrument gallery (HALCYON-INSTRUMENT 4.2) from the record.

One `usr/lib/halcyon/themes/<id>.toml` per theme in the `instrument-v1`
schema: the 35 colour roles from the round-2 sidecar
(`docs/halcyon-carbon-handoff/round2/ui-palettes/<id>.toml`, verbatim), the
authored ANSI-16 from `tools/halcyon/ansi16.json` (Appendix A's adopted
set), and `[type] smooth` by polarity (dark 0, light 12; HALCYON-TYPE 4.2).

Re-run after either input changes; the files are committed so the guest
and the tests read them, and `every_shipped_theme_loads` refuses a gallery
file whose id is not its filename. `--check` diffs instead of writing.
"""
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SIDECARS = ROOT / "docs/halcyon-carbon-handoff/round2/ui-palettes"
ANSI = ROOT / "tools/halcyon/ansi16.json"
OUT = ROOT / "usr/lib/halcyon/themes"

HEADER = """# {name} -- an Instrument theme ({word}; docs/HALCYON-INSTRUMENT.md 4.2).
#
# GENERATED by tools/halcyon/instrument-gallery.py from the record: the 35
# colour roles are docs/halcyon-carbon-handoff/round2/ui-palettes/{id}.toml
# verbatim, the ANSI-16 is tools/halcyon/ansi16.json (Appendix A), the
# smoothing stroke follows the polarity. Do not edit by hand -- change the
# record and re-run the tool. Loads only in a binary that knows this schema;
# an older one refuses it at the `profile` line, whole, which is the point.
"""


def render(id_, sidecar_text, ansi):
    doc = tomllib.loads(sidecar_text)
    meta, color = doc["meta"], doc["color"]
    assert meta["id"] == id_ and meta["profile"] == "instrument-v1" and meta["schema"] == 1
    assert set(doc) == {"meta", "color"} and len(color) == 35, id_
    light = meta["color_scheme"] == "light"
    lines = [HEADER.format(name=meta["name"], word=meta["profile"], id=id_)]
    lines.append("[meta]")
    for k in ("schema", "profile", "id", "name", "color_scheme"):
        lines.append(f"{k} = {json.dumps(meta[k], ensure_ascii=False)}")
    lines.append("")
    lines.append("[color]")
    for k, v in color.items():
        lines.append(f"{k} = {json.dumps(v)}")
    lines.append("")
    lines.append("[terminal]")
    lines.append("ansi = [" + ", ".join(json.dumps(c) for c in ansi) + "]")
    lines.append("")
    lines.append("[type]")
    lines.append(f"smooth = {12 if light else 0}")
    lines.append("")
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv[1:]
    ansi = json.loads(ANSI.read_text())
    bad = 0
    for path in sorted(SIDECARS.glob("*.toml")):
        id_ = path.stem
        assert len(ansi[id_]) == 16, id_
        text = render(id_, path.read_text(), ansi[id_])
        out = OUT / f"{id_}.toml"
        if check:
            if not out.exists() or out.read_text() != text:
                print(f"DRIFT {out}")
                bad += 1
        else:
            out.write_text(text)
            print(f"wrote {out.relative_to(ROOT)}")
    if check:
        print("OK" if not bad else f"PROBLEMS: {bad}")
        return 1 if bad else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
