#!/usr/bin/env python3
"""Write the Instrument gallery (HALCYON-INSTRUMENT 4.2) from the record.

One `usr/lib/halcyon/themes/<id>.toml` per theme in the `instrument-v1`
schema: the 35 colour roles from the round-2 sidecar
(`docs/halcyon-carbon-handoff/round2/ui-palettes/<id>.toml`, verbatim), the
authored ANSI-16 from `tools/halcyon/ansi16.json` (Appendix A's adopted
set), and `[type] smooth` by polarity (dark 0, light 12; HALCYON-TYPE 4.2).

Re-run after either input changes; the files are committed so the guest
and the tests read them, and `every_shipped_theme_loads` refuses a gallery
file whose id is not its filename. `--check` diffs instead of writing.
"""
import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SIDECARS = ROOT / "docs/halcyon-carbon-handoff/round2/ui-palettes"
ANSI = ROOT / "tools/halcyon/ansi16.json"
PICKER = ROOT / "tools/halcyon/picker.json"
OUT = ROOT / "usr/lib/halcyon/themes"
# The loader's own key table (`instrument::KEYS`), read from the source so the
# generator cannot drift from it: every `("color", "<name>")` row (r2 C-F4).
LOADER = ROOT / "usr/lib/libhalcyon/src/instrument.rs"
COLOR_KEYS = frozenset(re.findall(r'\("color", "([a-z_]+)"\)', LOADER.read_text()))
assert len(COLOR_KEYS) == 35, f"instrument::KEYS carries {len(COLOR_KEYS)} colour keys, not 35"
# The loader's colour grammar (`theme::parse_colour`): exactly `#RRGGBB`.
COLOUR = re.compile(r"#[0-9a-fA-F]{6}")

HEADER = """# {name} -- an Instrument theme ({word}; docs/HALCYON-INSTRUMENT.md 4.2).
#
# GENERATED by tools/halcyon/instrument-gallery.py from the record: the 35
# colour roles are docs/halcyon-carbon-handoff/round2/ui-palettes/{id}.toml
# verbatim, the ANSI-16 is tools/halcyon/ansi16.json (Appendix A), the
# smoothing stroke follows the polarity. Do not edit by hand -- change the
# record and re-run the tool. Loads only in a binary that knows this schema;
# an older one refuses it at the `profile` line, whole, which is the point.
"""


def render(id_, sidecar_text, ansi, picker):
    doc = tomllib.loads(sidecar_text)
    meta, color = doc["meta"], doc["color"]
    assert meta["id"] == id_ and meta["profile"] == "instrument-v1" and meta["schema"] == 1
    assert set(doc) == {"meta", "color"} and len(color) == 35, id_
    # The loader's own rules, so a regeneration fails HERE rather than at boot
    # (r1 B-F11; completed at r2 C-F4): a gallery id, sixteen distinct ANSI
    # colours, a presentable name of at most 64 BYTES (the loader's unit),
    # a polarity word the loader knows, the loader's 35 colour keys and no
    # other, every colour in its `#RRGGBB` grammar, and the 16 KiB cap
    # (checked on the rendered text below).
    assert re.fullmatch(r"[a-z][a-z0-9_-]{0,31}", id_), f"not a gallery id: {id_}"
    assert len(set(ansi)) == 16, f"ansi not distinct: {id_}"
    assert 1 <= len(meta["name"].encode()) <= 64 and meta["name"].isprintable(), f"name: {id_}"
    assert meta["color_scheme"] in ("dark", "light"), f"color_scheme: {id_}"
    assert set(color) == COLOR_KEYS, f"colour keys differ from the loader's: {id_}: {sorted(set(color) ^ COLOR_KEYS)}"
    for k, v in color.items():
        assert isinstance(v, str) and COLOUR.fullmatch(v), f"colour {k} = {v!r} is not #RRGGBB: {id_}"
    for v in ansi:
        assert isinstance(v, str) and COLOUR.fullmatch(v), f"ansi {v!r} is not #RRGGBB"
    light = meta["color_scheme"] == "light"
    lines = [HEADER.format(name=meta["name"], word=meta["profile"], id=id_)]
    lines.append("[meta]")
    for k in ("schema", "profile", "id", "name", "color_scheme"):
        lines.append(f"{k} = {json.dumps(meta[k], ensure_ascii=False)}")
    # HALCYON-INSTRUMENT 9.4 (I-7): the OPTIONAL picker keys, from picker.json.
    pk = picker.get(id_)
    if pk is not None:
        assert pk["group"] in ("dark", "terminal", "light"), f"group: {id_}"
        assert isinstance(pk["rank"], int) and 0 <= pk["rank"] <= 255, f"rank: {id_}"
        assert isinstance(pk["tagline"], str) and pk["tagline"].isprintable() and len(pk["tagline"].encode()) <= 64, f"tagline: {id_}"
        lines.append(f"group = {json.dumps(pk['group'])}")
        lines.append(f"tagline = {json.dumps(pk['tagline'], ensure_ascii=False)}")
        lines.append(f"rank = {pk['rank']}")
    lines.append("")
    lines.append("[color]")
    for k, v in color.items():
        lines.append(f"{k} = {json.dumps(v)}")
    lines.append("")
    lines.append("[terminal]")
    lines.append("ansi = [" + ", ".join(json.dumps(c) for c in ansi) + "]")
    lines.append("")
    lines.append("[type]")
    lines.append(f"smooth = {12 if light else 0}")
    lines.append("")
    text = "\n".join(lines)
    assert len(text.encode()) <= 16384, f"over INSTRUMENT_MAX: {id_}"
    return text


def main():
    check = "--check" in sys.argv[1:]
    ansi = json.loads(ANSI.read_text())
    picker = {k: v for k, v in json.loads(PICKER.read_text()).items() if not k.startswith("_")}
    bad = 0
    for path in sorted(SIDECARS.glob("*.toml")):
        id_ = path.stem
        assert len(ansi[id_]) == 16, id_
        text = render(id_, path.read_text(), ansi[id_], picker)
        out = OUT / f"{id_}.toml"
        if check:
            if not out.exists() or out.read_text() != text:
                print(f"DRIFT {out}")
                bad += 1
        else:
            out.write_text(text)
            print(f"wrote {out.relative_to(ROOT)}")
    if check:
        print("OK" if not bad else f"PROBLEMS: {bad}")
        return 1 if bad else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
