#!/usr/bin/env python3
"""Bake trusted Lex curiata type from repository-owned fonts (fonttools only).

Run manually when changing the type specification. Normal OS builds consume
the committed alpha masks, never a font parser or user-selected font. Uses the
same nonzero-winding, 4x supersampling rasterizer as Cornucopia.
"""
import importlib.util
import math
from pathlib import Path
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location("cornucopia_bake", ROOT / "tools/bake-cornucopia.py")
bake = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bake)
CHARS = list(range(32, 127)) + [0xb7, 0x2014]
SANS = "third_party/ibm-plex/ttf/IBMPlexSans-Regular.ttf"
TITLE = "third_party/ibm-plex/ttf/IBMPlexSans-Medium.ttf"
MONO = "usr/lib/cornucopia/src/cornucopia-subset.ttf"
FACES = [("Label", SANS, 12), ("Body", SANS, 14), ("Section", TITLE, 15),
         ("Identity", SANS, 18), ("Title", TITLE, 29),
         ("SmallMono", MONO, 10), ("Rail", MONO, 11), ("Mono", MONO, 14)]

def main():
    data = bytearray()
    records = []
    for name, path, size in FACES:
        font = TTFont(ROOT / path)
        cmap, glyphs = font.getBestCmap(), font.getGlyphSet()
        scale = size / font["head"].unitsPerEm
        # Two pixels of horizontal bearing room; a fixed line box per face.
        baseline = math.ceil(size * 1.05)
        height = math.ceil(size * 1.4)
        width = math.ceil(max(font["hmtx"][cmap[c]][0] for c in CHARS) * scale) + 4
        offset = len(data)
        for cp in CHARS:
            glyph = cmap[cp]
            advance = round(font["hmtx"][glyph][0] * scale)
            pen = bake.FlattenPen(glyphs, scale * bake.SS, baseline * bake.SS)
            glyphs[glyph].draw(pen)
            if pen.cur:
                pen.contours.append(pen.cur)
            contours = [[(x + 2 * bake.SS, y) for x, y in contour] for contour in pen.contours]
            grid = bake.rasterize(contours, width * bake.SS, height * bake.SS)
            data.append(advance)
            data.extend(bake.downsample(grid, width * bake.SS, height * bake.SS, width, height))
        records.append(f"    Font::{name} => ({offset}, {width}, {height}),")
    out = ROOT / "usr/lictor/src"
    (out / "type.bin").write_bytes(data)
    (out / "type_metrics.rs").write_text(
        "// Generated by tools/bake-lictor.py; do not edit.\n"
        "fn metrics(font: Font) -> (usize, usize, usize) { match font {\n"
        + "\n".join(records) + "\n} }\n")
    print(f"Baked {len(FACES)} faces, {len(CHARS)} glyphs each, {len(data)} bytes")

if __name__ == "__main__":
    main()
