#!/usr/bin/env bash
# Emit (and optionally exercise) the meson CROSS FILE for building Mesa/llvmpipe
# against aarch64-thylacine -- Clade CL-7a (docs/LLVM-DESIGN.md section 16.19).
#
# The cross file is GENERATED rather than checked in because every path in it is
# machine-local: the fork toolchain lives at $LLVMFORK on one machine and
# /build/src/llvm-thylacine on the builder. A checked-in file would be wrong on
# at least one of them, and wrong quietly.
#
# THE FLAGS ARE NOT FREE-CHOICE. They mirror build_clade's cross flags exactly,
# because Mesa's output links into the same Thylacine userspace as everything
# else. Two of them are load-bearing rather than stylistic:
#
#   -moutline-atomics : #71 (W1u) put all of userspace on the ARMv8.0 floor --
#                       LSE atomics are reached through outline helpers that
#                       check AT_HWCAP at runtime. A Mesa built without this
#                       emits bare LSE instructions that fault on an A72, and it
#                       would do so silently on an LSE-capable dev host. This is
#                       the regression #91 exists to guard.
#   -nostdlibinc      : the pouch sysroot must own every system header. Without
#     + -isystem        it, the host's /usr/include leaks in and the build fails
#                       far away from the cause (the CL-4 header-shadow gotcha).
#
# Verbs:
#   emit <path>   write the cross file, asserting every binary it names exists
#   show          print it to stdout
#
# Env: LLVMFORK, THYLA_ROOT (default: this repo), MESA_CROSS_SYSROOT.

set -euo pipefail

ROOT="${THYLA_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
FORK="${LLVMFORK:-$HOME/projects/llvm-thylacine}"
SHIM="$ROOT/tools/clade-llvm-config-cross.sh"
XTREE="${CLADE_LLVM_TARGET_TREE:-$ROOT/build/clade/llvm-build}"
XCACHE="$XTREE/CMakeCache.txt"

# EVERY PATH IS READ OUT OF THE CROSS LLVM'S OWN CMakeCache when one exists.
# Not for convenience: Mesa's objects get LINKED against that LLVM, so the cross
# file must name the same compiler, the same binutils and the same sysroot that
# built it. Deriving each from its own default is exactly how a cross file ends up
# describing a toolchain the LLVM was never built with -- and the resulting
# mismatch shows up as an inscrutable link or runtime failure, not a clear error.
cache_val() {
    [[ -f "$XCACHE" ]] || return 0
    sed -n "s|^$1:[A-Z]*=\(.*\)\$|\1|p" "$XCACHE" | head -1
}

CC="${POUCH_CC:-$(cache_val CMAKE_C_COMPILER)}";   CC="${CC:-$FORK/build/bin/clang}"
CXX="${POUCH_CXX:-$(cache_val CMAKE_CXX_COMPILER)}"; CXX="${CXX:-$FORK/build/bin/clang++}"
SYSROOT="${MESA_CROSS_SYSROOT:-$(cache_val CMAKE_SYSROOT)}"; SYSROOT="${SYSROOT:-$ROOT/build/sysroot}"
_ar="$(cache_val CMAKE_AR)"
if [[ -n "$_ar" ]]; then BINUTILS="$(dirname "$_ar")"
else BINUTILS="${LLVM_PREFIX:-/opt/homebrew/opt/llvm}/bin"; fi

die() { echo "clade-mesa-cross: FATAL: $*" >&2; exit 1; }

# Assert, do not assume. A cross file naming a missing compiler makes meson say
# "compiler not found" with no hint which of the four paths is wrong.
check() {
    local what="$1" p="$2"
    [[ -e "$p" ]] || die "$what not found: $p"
}

emit() {
    check "fork clang"      "$CC"
    check "fork clang++"    "$CXX"
    check "llvm-ar"         "$BINUTILS/llvm-ar"
    check "llvm-ranlib"     "$BINUTILS/llvm-ranlib"
    check "llvm-nm"         "$BINUTILS/llvm-nm"
    check "llvm-strip"      "$BINUTILS/llvm-strip"
    check "llvm-config shim" "$SHIM"
    check "sysroot headers" "$SYSROOT/include"
    check "sysroot libc++"  "$SYSROOT/include/c++/v1"
    check "libt syscall header (Warp-3 winsys)" "$ROOT/usr/lib/libt/include/thyla/syscall.h"

    cat <<EOF
# GENERATED by tools/clade-mesa-cross.sh -- do not edit; regenerate.
# Mesa/llvmpipe cross file for aarch64-thylacine (Clade CL-7a).

[binaries]
# THE TOOLCHAIN FLAGS LIVE HERE, NOT IN c_args, AND THAT IS LOAD-BEARING.
# Measured (CL-7a): meson's compiler-CHECK path drops the '-isystem <dir>' pair
# out of cross-file c_args while keeping every other flag -- so a check compiled
# with '-nostdlibinc' and no include path, and cc.get_define('ETIME') died on
# "'errno.h' file not found" at meson.build:1111, nowhere near the real cause.
# (The sanity check DOES get the full list, so the two paths disagree; the obvious
# suspect, remove_linkerlike_args, filters none of these -- the drop is elsewhere
# in meson's CompilerArgs machinery, and is not worth chasing further because the
# exelist is immune: --target= and --sysroot= survived every path.)
#
# The same immunity is why -moutline-atomics belongs here: it is a flag whose
# absence compiles perfectly and faults on an A72 (#71/#91), so it must not sit
# anywhere a build system is free to filter it.
c = ['$CC', '--target=aarch64-thylacine', '--sysroot=$SYSROOT', '-march=armv8-a', '-moutline-atomics', '-fno-pic', '-nostdlibinc', '-isystem', '$SYSROOT/include']
cpp = ['$CXX', '--target=aarch64-thylacine', '--sysroot=$SYSROOT', '-march=armv8-a', '-moutline-atomics', '-fno-pic', '-nostdlibinc', '-isystem', '$SYSROOT/include/c++/v1', '-isystem', '$SYSROOT/include']
ar = '$BINUTILS/llvm-ar'
ranlib = '$BINUTILS/llvm-ranlib'
strip = '$BINUTILS/llvm-strip'
nm = '$BINUTILS/llvm-nm'
# The cross llvm-config: the cross tree's own is an aarch64-thylacine binary the
# builder cannot run, and the fork's host one answers with host paths.
llvm-config = '$SHIM'
# Mesa's build needs these on the BUILD machine, not the host machine.
python = 'python3'

[built-in options]
# Only the defines stay here -- everything structural is in the exelist above.
# The libt include is the ONE path exception (Warp-3): the virgl winsys's
# warp_client.c speaks raw Thylacine syscalls via <thyla/syscall.h>, and that
# header lives in the Thylacine repo, which is machine-local -- exactly what
# this generated file exists to carry. Single token ('-Ipath', no space) on
# purpose: meson's compiler-CHECK path drops two-token '-isystem <dir>' pairs
# from cross-file c_args (measured, see the exelist comment) and a glued -I
# is immune the same way --sysroot= is.
c_args = ['-D_GNU_SOURCE=1', '-I$ROOT/usr/lib/libt/include']
cpp_args = ['-D_GNU_SOURCE=1']
# gallivm's ORC backend uses dynamic_cast on llvm::orc types, so RTTI must be ON
# here AND in the LLVM being linked. LLVM defaults it OFF; build_clade turns it
# on for exactly this reason, and the shim reports the cross tree's real setting
# so a mismatch is caught at configure instead of at link.
cpp_rtti = true
# Thylacine has no dynamic loader (kernel/elf.c requires ET_EXEC with no
# PT_DYNAMIC), so there is no shared-library form of anything.
default_library = 'static'
prefer_static = true

[properties]
needs_exe_wrapper = true
sys_root = '$SYSROOT'

[host_machine]
# 'linux' rather than 'thylacine' DELIBERATELY: Mesa branches on
# host_machine.system() in ~40 places, and the linux arm is the one that assumes
# a musl/glibc-shaped POSIX -- which is exactly what pouch presents. An unknown
# system name falls into else-branches written for Windows/Haiku. The risk this
# accepts is a linux-only assumption reaching the build (dlopen, DRM, epoll);
# option (i) exists precisely to avoid the loader, so that risk is bounded --
# and if the configure surfaces one, the honest fix is a Mesa-side guard, not a
# different system name.
system = 'linux'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'
EOF
}

case "${1:-show}" in
    show) emit ;;
    emit)
        out="${2:-}"
        [[ -n "$out" ]] || die "usage: $0 emit <path>"
        emit > "$out"
        echo "wrote $out"
        ;;
    *) die "unknown verb '${1}' (want: emit <path> | show)" ;;
esac
