#!/usr/bin/env python3
# Halls of Extinction -- Tier-2 symbol-table generator (HX-2).
#
# Reads `llvm-nm --defined-only <kernel.elf>` on stdin and emits, on stdout, the
# C source for the in-kernel symbol table consumed by arch/arm64/halls_symtab.h
# / halls_symbolize(). tools/build.sh drives the two-pass build: link with the
# stub -> run this over the ELF -> overwrite <build>/generated/halls_symtab.c ->
# re-link. The table lives in .rodata (after .text per kernel.ld), so the
# symbolized .text addresses do not move across that re-link -> it converges in
# one re-link (build.sh asserts stability with a second pass).
#
# Output is DETERMINISTIC (sorted, deduped, no timestamps) so the stability
# check is a byte-compare and builds are reproducible.
#
# Encoding rationale: addresses are stored as u32 OFFSETS from the minimum text
# address (== _start == KERNEL_LINK_VA), NOT absolute u64 VAs, so the table is
# PIE-reloc-free + KASLR-independent (see halls_symtab.h). The base is emitted
# as halls_symtab_link_base; halls_symbolize() subtracts it from the
# KASLR-translated query address.

import sys

U32_MAX = 0xFFFFFFFF


def parse_nm(stream):
    syms = []  # (addr:int, name:str)
    for line in stream:
        # split(None, 2) keeps a name intact even if it contained whitespace
        # (dormant -- nm runs WITHOUT -C, so names are mangled; F2). rstrip
        # drops the trailing newline.
        parts = line.split(None, 2)
        if len(parts) < 3:
            continue                      # undefined / no-address line
        addr_s, typ, name = parts[0], parts[1], parts[2].rstrip()
        if typ not in ("t", "T"):         # text (code) symbols only
            continue
        if not name or name[0] == "$":    # ARM mapping symbols ($x/$d) -> noise
            continue
        try:
            addr = int(addr_s, 16)
        except ValueError:
            continue
        syms.append((addr, name))
    return syms


def c_escape_bytes(bs):
    # Escape a byte string for a C string literal, ONE emitted token per BYTE
    # (printable ASCII verbatim, else a 1-byte octal escape). So the compiled
    # blob has exactly len(bs) bytes -- the property name_off accounting relies
    # on. Iterating per byte (not per code point) is the HX-2 audit F1 fix: a
    # code point >= 0x80 emits as a single \NNN (1 byte) but is multiple UTF-8
    # bytes, so a per-code-point escape diverged from a per-UTF-8-byte length.
    out = []
    for b in bs:
        if b == 0x5C:               # backslash
            out.append("\\\\")
        elif b == 0x22:             # double quote
            out.append('\\"')
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\%03o" % b)
    return "".join(out)


def emit_stub():
    return (
        "// GENERATED by tools/gen-halls-symtab.py -- no text symbols found.\n"
        '#include "halls_symtab.h"\n'
        "const u64               halls_symtab_link_base = 0;\n"
        "const u32               halls_symtab_count     = 0;\n"
        "const struct halls_sym  halls_symtab[1]        = { { 0, 0 } };\n"
        "const char              halls_symtab_names[1]  = { 0 };\n"
    )


def main():
    syms = parse_nm(sys.stdin)
    if not syms:
        sys.stdout.write(emit_stub())
        return 0

    base = min(a for a, _ in syms)

    # Sort by (addr, name); dedup by address (keep the alphabetically-first
    # name at each address, so duplicates like _start/_kernel_start are stable).
    syms.sort(key=lambda s: (s[0], s[1]))
    deduped = []
    last_addr = None
    for addr, name in syms:
        if addr == last_addr:
            continue
        off = addr - base
        if off > U32_MAX:                 # outside the u32-offset window -> skip
            continue
        deduped.append((off, name))
        last_addr = addr

    # Name blob: NUL-separated raw bytes, identical names coalesced. name_off is
    # the byte offset into this bytearray; BOTH the offset and the emitted C
    # literal are derived from the SAME bytes below, so they cannot diverge
    # (HX-2 audit F1). The implicit trailing NUL the C compiler appends is
    # harmless (one byte past the last name's own NUL, never indexed).
    name_to_off = {}
    blob = bytearray()
    table = []  # (off, name_off)
    for off, name in deduped:
        if name not in name_to_off:
            name_to_off[name] = len(blob)
            blob += name.encode("utf-8") + b"\x00"
        table.append((off, name_to_off[name]))
    # Self-check: every name resolves to its exact NUL-terminated bytes -- makes
    # the F1 offset/emission divergence impossible to reintroduce silently.
    for name, noff in name_to_off.items():
        nb = name.encode("utf-8")
        assert blob[noff:noff + len(nb)] == nb and blob[noff + len(nb)] == 0, \
            "halls symtab name_off self-check failed for %r" % name

    # F3: soft-budget warning so an oversized table self-describes on stderr
    # BEFORE it trips the generic 4 MiB L3-mapping ASSERT in kernel.ld (the hard
    # guard). 1 MiB is ~18x the current ~55 KiB -- a real "something is wrong"
    # signal with ample margin below the image cap.
    approx = len(table) * 8 + len(blob)
    if approx > (1 << 20):
        sys.stderr.write(
            "==> HX-2 WARNING: symbol table ~%u KiB (%u syms) -- approaching the "
            "kernel.ld 4 MiB L3 image cap; consider trimming\n"
            % (approx // 1024, len(table)))

    out = []
    out.append("// GENERATED by tools/gen-halls-symtab.py from the linked kernel ELF -- do not edit.")
    out.append("// HX-2 in-kernel symbol table; see arch/arm64/halls_symtab.h + docs/reference/101-halls.md.")
    out.append('#include "halls_symtab.h"')
    out.append("")
    out.append("const u64 halls_symtab_link_base = 0x%016xull;" % base)
    out.append("const u32 halls_symtab_count     = %uu;" % len(table))
    out.append("")
    out.append("const struct halls_sym halls_symtab[%uu] = {" % len(table))
    for off, name_off in table:
        out.append("    { 0x%xu, 0x%xu }," % (off, name_off))
    out.append("};")
    out.append("")
    out.append("const char halls_symtab_names[] =")
    # Emit the blob byte-for-byte as adjacent "..." literals (the compiler
    # concatenates them). A fixed byte-chunk per line keeps the file legible +
    # deterministic; a chunk boundary never splits an escape (each byte escapes
    # to a whole token).
    CHUNK = 24
    for i in range(0, len(blob), CHUNK):
        out.append('    "%s"' % c_escape_bytes(blob[i:i + CHUNK]))
    out.append("    ;")
    out.append("")
    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
