#!/usr/bin/env python3
# Halls of Extinction -- Tier-2 symbol-table generator (HX-2).
#
# Reads `llvm-nm --defined-only <kernel.elf>` on stdin and emits, on stdout, the
# C source for the in-kernel symbol table consumed by arch/arm64/halls_symtab.h
# / halls_symbolize(). tools/build.sh drives the two-pass build: link with the
# stub -> run this over the ELF -> overwrite <build>/generated/halls_symtab.c ->
# re-link. The table lives in .rodata (after .text per kernel.ld), so the
# symbolized .text addresses do not move across that re-link -> it converges in
# one re-link (build.sh asserts stability with a second pass).
#
# Output is DETERMINISTIC (sorted, deduped, no timestamps) so the stability
# check is a byte-compare and builds are reproducible.
#
# Encoding rationale: addresses are stored as u32 OFFSETS from the minimum text
# address (== _start == KERNEL_LINK_VA), NOT absolute u64 VAs, so the table is
# PIE-reloc-free + KASLR-independent (see halls_symtab.h). The base is emitted
# as halls_symtab_link_base; halls_symbolize() subtracts it from the
# KASLR-translated query address.

import sys

U32_MAX = 0xFFFFFFFF


def parse_nm(stream):
    syms = []  # (addr:int, name:str)
    for line in stream:
        parts = line.split()
        if len(parts) < 3:
            continue                      # undefined / no-address line
        addr_s, typ, name = parts[0], parts[1], parts[2]
        if typ not in ("t", "T"):         # text (code) symbols only
            continue
        if not name or name[0] == "$":    # ARM mapping symbols ($x/$d) -> noise
            continue
        try:
            addr = int(addr_s, 16)
        except ValueError:
            continue
        syms.append((addr, name))
    return syms


def c_escape(name):
    out = []
    for ch in name:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= ord(ch) < 0x7F:
            out.append(ch)
        else:
            out.append("\\%03o" % ord(ch))   # octal escape for anything exotic
    return "".join(out)


def emit_stub():
    return (
        "// GENERATED by tools/gen-halls-symtab.py -- no text symbols found.\n"
        '#include "halls_symtab.h"\n'
        "const u64               halls_symtab_link_base = 0;\n"
        "const u32               halls_symtab_count     = 0;\n"
        "const struct halls_sym  halls_symtab[1]        = { { 0, 0 } };\n"
        "const char              halls_symtab_names[1]  = { 0 };\n"
    )


def main():
    syms = parse_nm(sys.stdin)
    if not syms:
        sys.stdout.write(emit_stub())
        return 0

    base = min(a for a, _ in syms)

    # Sort by (addr, name); dedup by address (keep the alphabetically-first
    # name at each address, so duplicates like _start/_kernel_start are stable).
    syms.sort(key=lambda s: (s[0], s[1]))
    deduped = []
    last_addr = None
    for addr, name in syms:
        if addr == last_addr:
            continue
        off = addr - base
        if off > U32_MAX:                 # outside the u32-offset window -> skip
            continue
        deduped.append((off, name))
        last_addr = addr

    # Name blob: NUL-separated, with identical names coalesced. Each entry's
    # name_off is the byte offset of its NUL-terminated name. Emitted as adjacent
    # "name\0" string literals (the compiler concatenates them; the one implicit
    # trailing NUL is harmless).
    name_to_off = {}
    blob_literals = []
    blob_len = 0
    table = []  # (off, name_off)
    for off, name in deduped:
        if name not in name_to_off:
            name_to_off[name] = blob_len
            blob_literals.append('"%s\\0"' % c_escape(name))
            blob_len += len(name.encode("utf-8")) + 1
        table.append((off, name_to_off[name]))

    out = []
    out.append("// GENERATED by tools/gen-halls-symtab.py from the linked kernel ELF -- do not edit.")
    out.append("// HX-2 in-kernel symbol table; see arch/arm64/halls_symtab.h + docs/reference/101-halls.md.")
    out.append('#include "halls_symtab.h"')
    out.append("")
    out.append("const u64 halls_symtab_link_base = 0x%016xull;" % base)
    out.append("const u32 halls_symtab_count     = %uu;" % len(table))
    out.append("")
    out.append("const struct halls_sym halls_symtab[%uu] = {" % len(table))
    for off, name_off in table:
        out.append("    { 0x%xu, 0x%xu }," % (off, name_off))
    out.append("};")
    out.append("")
    out.append("const char halls_symtab_names[] =")
    # Wrap the blob literals ~6 per line for a legible (but still deterministic)
    # generated file.
    line = "    "
    per_line = 0
    for lit in blob_literals:
        line += lit + " "
        per_line += 1
        if per_line == 6:
            out.append(line.rstrip())
            line = "    "
            per_line = 0
    if per_line:
        out.append(line.rstrip())
    out.append("    ;")
    out.append("")
    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
